/* eslint-env node */
const {chromium,request}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const api=await request.newContext({baseURL:'http://127.0.0.1:18001',extraHTTPHeaders:{'X-User-Role':'admin'}});
 async function post(path,data){const r=await api.post('/api/v1'+path,{data});assert(r.ok(),await r.text());return r.json();}
 const tag=Date.now(),username='execution-'+tag,password='Execution-test-123!';
 const supplier=await post('/suppliers',{code:'EX-S-'+tag,name:'交付验收供应商',status:'qualified'});
 assert((await api.put('/api/v1/supplier-accounts',{data:{supplier_id:supplier.id,username,password}})).ok());
 const order=await post('/orders',{supplier_id:supplier.code,supplier_name:supplier.name,factory_code:'F1',lines:[{material_code:'EX-M-'+tag,material_name:'验收物料',quantity:5,unit:'件',unit_price:20}]});
 assert((await api.patch('/api/v1/orders/'+order.id,{data:{status:'sent'}})).ok());
 const recon=await post('/reconciliations',{order_id:order.id,amount:100});await post('/reconciliations/'+recon.id+'/confirm',{});
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/api/v1/**',async route=>{const u=new URL(route.request().url());const r=await route.fetch({url:'http://127.0.0.1:18001'+u.pathname+u.search});await route.fulfill({response:r});});
 async function field(dialog,label,value){const item=dialog.locator('.el-form-item').filter({has:page.locator('.el-form-item__label',{hasText:label})});await item.locator('input').first().fill(value);await item.locator('input').first().press('Tab');}
 try{
  await page.goto('http://localhost:8080/supplier',{waitUntil:'networkidle'});await page.locator('.login-card input').nth(0).fill(username);await page.locator('.login-card input').nth(1).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('tab',{name:'订单交付',exact:true}).click();await page.getByRole('button',{name:'确认接单',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'确定',exact:true}).click();await page.getByRole('button',{name:'登记发货',exact:true}).click();
  let dialog=page.locator('.el-dialog:visible').last();await field(dialog,'本次发货数量','3');await field(dialog,'承运商','验收物流');await field(dialog,'运单号','TEST-TRACK-'+tag);await field(dialog,'发货日期','2026-09-04');await field(dialog,'预计到货日期','2026-09-05');await dialog.getByRole('button',{name:'提交',exact:true}).click();await page.getByText('发货预通知已发送，等待采购方收货',{exact:true}).waitFor();await page.locator('.el-table__row').filter({hasText:'TEST-TRACK-'+tag}).waitFor();await page.screenshot({path:'/tmp/pebs-supplier-delivery.png',fullPage:true});
  await page.goto('http://localhost:8080/fulfillment',{waitUntil:'networkidle'});await page.getByRole('button',{name:'供应商交付记录',exact:true}).click();dialog=page.locator('.el-dialog:visible').last();await dialog.getByRole('button',{name:'确认实际收货',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'确定',exact:true}).click();await page.getByText('收货已确认，请继续进行质量检验',{exact:true}).waitFor();
  await page.goto('http://localhost:8080/supplier',{waitUntil:'networkidle'});await page.getByRole('tab',{name:'发票上传',exact:true}).click();await page.getByRole('button',{name:'上传发票',exact:true}).click();dialog=page.locator('.el-dialog:visible').last();await dialog.locator('.el-select').click();await page.locator('.el-select-dropdown:visible').getByText(new RegExp(recon.reconciliation_no)).click();await field(dialog,'发票号码','EX-INVOICE-'+tag);await field(dialog,'含税金额','60');await field(dialog,'税额','6');await field(dialog,'开票日期','2026-09-04');await dialog.locator('input[type=file]').setInputFiles({name:'invoice.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await dialog.getByRole('button',{name:'提交',exact:true}).click();await page.getByText('发票已上传，等待采购方审核',{exact:true}).waitFor();await page.locator('.el-table__row').filter({hasText:'EX-INVOICE-'+tag}).waitFor();await page.screenshot({path:'/tmp/pebs-supplier-invoice.png',fullPage:true});
  await page.goto('http://localhost:8080/settlements',{waitUntil:'networkidle'});await page.getByRole('tab',{name:'供应商发票',exact:true}).click();const row=page.locator('.el-table__row').filter({hasText:'EX-INVOICE-'+tag});await row.first().waitFor();const [download]=await Promise.all([page.waitForEvent('download'),row.getByRole('button',{name:'下载发票',exact:true}).first().click()]);assert.equal(download.suggestedFilename(),'invoice.pdf');await row.getByRole('button',{name:'验真',exact:true}).first().click();await page.getByText('状态已更新',{exact:true}).waitFor();
  await page.goto('http://localhost:8080/supplier',{waitUntil:'networkidle'});await page.getByRole('tab',{name:'发票上传',exact:true}).click();await page.locator('.el-table__row').filter({hasText:'EX-INVOICE-'+tag}).getByText('已验真',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS supplier order confirmation, shipment, buyer receipt, invoice upload/download/review and supplier status sync');
 }catch(e){await page.screenshot({path:'/tmp/pebs-supplier-execution-failure.png',fullPage:true});throw e;}finally{await browser.close();await api.dispose();}
})().catch(e=>{console.error(e);process.exit(1);});
