<template>
  <div><el-alert title="供货反馈接入：ERP / MES / WMS / QMS。支持外部系统主动推送统一JSON，或人工导入CSV；不自动拉取第三方数据。" type="info" :closable="false"/><div style="margin:16px 0"><el-button @click="downloadTemplate">下载导入模板（CSV）</el-button><el-button @click="guideVisible=true">设置说明 / 字段字典</el-button><el-button @click="demo">生成模拟分析数据</el-button></div>
    <template v-if="connector"><h3>{{connector.name}}</h3><p>接入地址：{{endpoint}}</p><p>状态：{{access.status}}；专用令牌：{{access.token_set?'已配置':'未配置'}}。只有已启用连接器可以接收数据。</p><el-button :loading="busy" @click="rotate">生成 / 轮换专用令牌</el-button><el-input v-if="token" :value="token" readonly type="textarea"/><p v-if="token">令牌仅显示本次，请复制到外部系统的安全配置中，切勿放入业务文件。</p><el-upload action="#" :http-request="upload" :show-file-list="false" accept=".csv" :disabled="busy"><el-button type="primary" :loading="busy">导入供货反馈 CSV</el-button></el-upload><p>{{importResult}}</p></template><p v-else>点击连接器行的“供货反馈接入”，配置对应令牌并导入。</p>
    <ListFilters :only-resources="['supply-feedback/records']" @query="pagination.page=1;load()"/><el-table :data="records" border max-height="360"><el-table-column prop="external_id" label="批次ID"/><el-table-column prop="supplier_code" label="供应商编码"/><el-table-column prop="material_code" label="物料编码"/><el-table-column prop="source_system" label="来源"/><el-table-column prop="record_date" label="业务日期"/><el-table-column label="类型"><template slot-scope="s">{{s.row.is_demo?'模拟':'导入/推送'}}</template></el-table-column></el-table><Pager :page="pagination" @change="changePage" @size="changeSize"/>
    <el-dialog title="供货反馈设置说明与导入字段" :visible.sync="guideVisible" width="920px" append-to-body><p v-for="(line,i) in guide.instructions" :key="i">{{i+1}}. {{line}}</p><el-table :data="guide.fields" max-height="350"><el-table-column prop="name" label="字段" width="190"/><el-table-column label="必填" width="65"><template slot-scope="s">{{s.row.required?'是':'否'}}</template></el-table-column><el-table-column prop="description" label="填写说明"/></el-table><h3>JSON推送示例</h3><pre style="white-space:pre-wrap">POST {{endpoint||'/api/v1/integration-feedback/{connector_id}'}}
Authorization: Bearer &lt;专用令牌&gt;
Content-Type: application/json
{{JSON.stringify(guide.example,null,2)}}</pre><span slot="footer"><el-button @click="guideVisible=false">关闭</el-button></span></el-dialog>
  </div>
</template>
<script>
import ListFilters from './ListFilters.vue';
import {api} from '../api/client';import Pager from './Pager.vue';
export default {components:{ListFilters,Pager},props:{connector:Object},data:()=>({guide:{},guideVisible:false,access:{},token:'',busy:false,records:[],importResult:'',pagination:{page:1,page_size:10,total:0}}),computed:{endpoint(){return this.access.endpoint?new URL(this.access.endpoint,window.location.origin).href:'';}},async created(){try{this.guide=(await api.get('/supply-feedback/guide')).data;if(this.connector)this.access=(await api.get(`/data-connectors/${this.connector.id}/feedback-access`)).data;await this.load();}catch(e){this.error(e);}},methods:{error(e){const d=e.response?.data?.detail;this.$message.error(typeof d==='string'?d:'操作失败');},async load(){try{const r=(await api.get('/supply-feedback/records',{params:{...this.pagination,connector_id:this.connector?.id||''}})).data;this.records=r.items;this.pagination.total=r.total;}catch(e){this.error(e);}},changePage(p){this.pagination.page=p;this.load();},changeSize(n){this.pagination.page=1;this.pagination.page_size=n;this.load();},async downloadTemplate(){try{const r=await api.get('/supply-feedback/template',{responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='supply-feedback-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){this.error(e);}},async rotate(){try{await this.$confirm('轮换后旧令牌立即失效，确认继续？','接入令牌');this.busy=true;const r=(await api.post(`/data-connectors/${this.connector.id}/feedback-token`)).data;this.token=r.token;this.access.token_set=true;}catch(e){if(e!=='cancel')this.error(e);}finally{this.busy=false;}},async upload(options){this.busy=true;try{const f=new FormData();f.append('file',options.file);const r=(await api.post(`/data-connectors/${this.connector.id}/feedback-import`,f)).data;this.importResult=`新增 ${r.inserted} 条，重复跳过 ${r.skipped} 条`;this.$message.success(this.importResult);await this.load();}catch(e){this.error(e);}finally{this.busy=false;}},async demo(){try{await this.$confirm('将新增明确标记的模拟供应商、物料、询价和144批反馈，不发送邮件，不覆盖原数据。','生成模拟数据');const r=(await api.post('/supply-feedback/demo')).data;this.$message.success(`新增 ${r.inserted} 条模拟反馈；在分析页勾选包含模拟数据查看`);await this.load();this.$emit('refresh');}catch(e){if(e!=='cancel')this.error(e);}}}};
</script>
