<template>
  <div class="tech-docs" v-loading="loading">
    <div class="material-head"><div><p class="eyebrow">TECHNICAL DOCUMENT CONTROL</p><h3>{{ material.code }} · {{ material.name }}</h3><p>{{ material.specification || '未填写规格型号' }}</p></div><el-button type="primary" @click="openCreate">上传技术资料</el-button></div>
    <el-alert title="资料按“资料编号＋版本”受控；新版本审批生效后，同编号旧版自动作废。" type="info" :closable="false" show-icon/>
    <div class="counts"><button v-for="item in statusCards" :key="item.value" @click="setStatus(item.value)"><span>{{ item.label }}</span><strong>{{ counts[item.value] || 0 }}</strong></button></div>
    <div class="toolbar"><el-input v-model.trim="keyword" clearable placeholder="搜索资料编号、标题或版本" @keyup.enter.native="search" @clear="search"/><el-select v-model="type" clearable placeholder="全部资料类型" @change="search"><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-select v-model="status" clearable placeholder="全部状态" @change="search"><el-option v-for="item in statuses" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-button icon="el-icon-search" @click="search">查询</el-button></div>
    <el-table :data="items" size="small" empty-text="该物料暂无技术资料">
      <el-table-column prop="document_no" label="资料编号" width="145"/><el-table-column prop="title" label="资料名称" min-width="170" show-overflow-tooltip/><el-table-column label="类型" width="110"><template slot-scope="s">{{ typeName(s.row.document_type) }}</template></el-table-column><el-table-column prop="version" label="版本" width="75"/><el-table-column label="状态" width="95"><template slot-scope="s"><el-tag size="mini" :type="statusType(s.row.status)">{{ statusName(s.row.status) }}</el-tag></template></el-table-column><el-table-column prop="effective_date" label="生效日期" width="105"><template slot-scope="s">{{ s.row.effective_date || '-' }}</template></el-table-column><el-table-column label="文件" min-width="165"><template slot-scope="s"><el-button type="text" @click="download(s.row)">{{ s.row.file_name }}</el-button><small>{{ fileSize(s.row.file_size) }}</small></template></el-table-column>
      <el-table-column label="操作" width="235" fixed="right"><template slot-scope="s"><el-button v-if="s.row.status==='draft'" type="text" @click="edit(s.row)">编辑</el-button><el-button v-if="s.row.status==='draft'" type="text" @click="submit(s.row)">提交</el-button><el-button v-if="s.row.status==='pending_approval'" type="text" @click="review(s.row)">审批</el-button><el-button type="text" @click="history(s.row)">历史</el-button><el-button v-if="s.row.status==='draft'" type="text" class="danger" @click="remove(s.row)">删除</el-button></template></el-table-column>
    </el-table>
    <div class="pager"><span>共 {{ pagination.total }} 条</span><el-pagination small background layout="prev, pager, next" :current-page="pagination.page" :page-size="pagination.page_size" :total="pagination.total" @current-change="changePage"/></div>

    <el-dialog :title="form.id?'编辑技术资料':'上传技术资料'" :visible.sync="formVisible" width="650px" append-to-body :close-on-click-modal="false"><el-form ref="form" :model="form" :rules="rules" label-width="100px"><el-row :gutter="14"><el-col :span="12"><el-form-item label="资料编号" prop="document_no"><el-input v-model.trim="form.document_no" :disabled="!!form.id" placeholder="如 DWG-MRO-001"/></el-form-item></el-col><el-col :span="12"><el-form-item label="版本号" prop="version"><el-input v-model.trim="form.version" :disabled="!!form.id" placeholder="如 1.0 或 A"/></el-form-item></el-col></el-row><el-form-item label="资料名称" prop="title"><el-input v-model.trim="form.title"/></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="资料类型" prop="document_type"><el-select v-model="form.document_type" style="width:100%"><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="生效日期"><el-date-picker v-model="form.effective_date" value-format="yyyy-MM-dd" type="date" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="资料说明"><el-input v-model.trim="form.description" type="textarea" :rows="3" maxlength="2000" show-word-limit/></el-form-item><el-form-item v-if="!form.id" label="技术文件" prop="file"><input ref="file" type="file" accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg,.dwg,.dxf" @change="pickFile"><p class="tip">支持PDF、Word、Excel、图片、DWG、DXF，最大20MB</p></el-form-item></el-form><span slot="footer"><el-button @click="formVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存草稿</el-button></span></el-dialog>
    <el-dialog title="技术资料审批" :visible.sync="reviewVisible" width="550px" append-to-body><template v-if="selected"><el-alert :title="`${selected.document_no} V${selected.version} · ${selected.title}`" type="info" :closable="false"/><el-input v-model.trim="decision.note" type="textarea" :rows="4" class="review-note" placeholder="填写审批意见；驳回时必填"/></template><span slot="footer"><el-button @click="reviewVisible=false">取消</el-button><el-button :loading="saving" @click="decide(false)">驳回修改</el-button><el-button type="success" :loading="saving" @click="decide(true)">批准生效</el-button></span></el-dialog>
    <el-dialog title="技术资料流转历史" :visible.sync="historyVisible" width="820px" append-to-body><el-table :data="historyItems" size="small"><el-table-column label="时间" width="175"><template slot-scope="s">{{ formatTime(s.row.created_at) }}</template></el-table-column><el-table-column label="动作" width="100"><template slot-scope="s">{{ actionName(s.row.action) }}</template></el-table-column><el-table-column label="状态" width="100"><template slot-scope="s"><el-tag size="mini" :type="statusType(s.row.status)">{{ statusName(s.row.status) }}</el-tag></template></el-table-column><el-table-column prop="actor_id" label="操作人" width="130"/><el-table-column prop="note" label="说明" min-width="220" show-overflow-tooltip/></el-table></el-dialog>
  </div>
</template>

<script>
import { api } from "../api/client";
const fresh = () => ({ id: "", document_no: "", title: "", document_type: "drawing", version: "1.0", effective_date: "", description: "", file: null });
export default {
  props: { material: { type: Object, required: true } },
  data: () => ({ items: [], counts: {}, keyword: "", type: "", status: "", loading: false, saving: false, formVisible: false, reviewVisible: false, historyVisible: false, form: fresh(), selected: null, decision: { note: "" }, historyItems: [], pagination: { page: 1, page_size: 10, total: 0 }, types: [{ value: "drawing", label: "设计图纸" }, { value: "specification", label: "技术规格书" }, { value: "inspection_standard", label: "检验标准" }, { value: "certificate", label: "材质/合格证明" }, { value: "process_instruction", label: "工艺指导书" }, { value: "other", label: "其他资料" }], statuses: [{ value: "draft", label: "草稿" }, { value: "pending_approval", label: "待审批" }, { value: "active", label: "已生效" }, { value: "obsolete", label: "已作废" }], rules: { document_no: [{ required: true, message: "请输入资料编号", trigger: "blur" }], version: [{ required: true, message: "请输入版本号", trigger: "blur" }], title: [{ required: true, message: "请输入资料名称", trigger: "blur" }], document_type: [{ required: true, message: "请选择资料类型", trigger: "change" }], file: [{ validator: (_rule, _value, callback) => callback(), trigger: "change" }] } }),
  computed: { statusCards() { return this.statuses; } },
  created() { this.load(); },
  methods: {
    error(e) { this.$message.error(e.response?.data?.detail || "操作失败"); }, typeName(v) { return this.types.find(item => item.value === v)?.label || v; }, statusName(v) { return this.statuses.find(item => item.value === v)?.label || v; }, statusType(v) { return { draft: "info", pending_approval: "warning", active: "success", obsolete: "danger" }[v] || "info"; }, actionName(v) { return { create: "创建", update: "修改", submit: "提交", approve: "批准", reject: "驳回", obsolete: "版本替代" }[v] || v; }, fileSize(v) { return v >= 1048576 ? `${(v / 1048576).toFixed(1)}MB` : `${Math.max(1, Math.round(v / 1024))}KB`; }, formatTime(v) { return v ? new Date(v).toLocaleString("zh-CN", { hour12: false }) : "-"; },
    async load() { this.loading = true; try { const { data } = await api.get(`/materials/${this.material.id}/technical-documents`, { params: { ...this.pagination, keyword: this.keyword, document_type: this.type, status: this.status } }); this.items = data.items; this.counts = data.counts; this.pagination.total = data.total; } catch (e) { this.error(e); } finally { this.loading = false; } },
    search() { this.pagination.page = 1; this.load(); }, changePage(v) { this.pagination.page = v; this.load(); }, setStatus(v) { this.status = this.status === v ? "" : v; this.search(); }, openCreate() { this.form = fresh(); this.formVisible = true; this.$nextTick(() => { if (this.$refs.file) this.$refs.file.value = ""; }); }, edit(row) { this.form = { ...row, file: null }; this.formVisible = true; }, pickFile(e) { this.form.file = e.target.files?.[0] || null; },
    save() { this.$refs.form.validate(async valid => { if (!valid) return; if (!this.form.id && !this.form.file) return this.$message.warning("请选择技术文件"); this.saving = true; try { if (this.form.id) { await api.patch(`/material-technical-documents/${this.form.id}`, { title: this.form.title, document_type: this.form.document_type, effective_date: this.form.effective_date || null, description: this.form.description || "" }); } else { const data = new FormData(); ["document_no", "title", "document_type", "version", "effective_date", "description"].forEach(key => data.append(key, this.form[key] || "")); data.append("file", this.form.file); await api.post(`/materials/${this.material.id}/technical-documents`, data, { headers: { "Content-Type": "multipart/form-data" } }); } this.formVisible = false; await this.load(); this.$message.success("技术资料草稿已保存"); } catch (e) { this.error(e); } finally { this.saving = false; } }); },
    async submit(row) { try { await this.$confirm(`提交 ${row.document_no} V${row.version} 审批？`, "提交审批", { type: "warning" }); await api.post(`/material-technical-documents/${row.id}/submit`); await this.load(); this.$message.success("技术资料已提交审批"); } catch (e) { if (e !== "cancel") this.error(e); } }, review(row) { this.selected = row; this.decision = { note: "" }; this.reviewVisible = true; }, async decide(approved) { if (!approved && !this.decision.note) return this.$message.warning("驳回必须填写原因"); this.saving = true; try { await api.post(`/material-technical-documents/${this.selected.id}/decision`, { approved, note: this.decision.note }); this.reviewVisible = false; await this.load(); this.$message.success(approved ? "技术资料已批准生效" : "技术资料已驳回草稿"); } catch (e) { this.error(e); } finally { this.saving = false; } },
    async download(row) { try { const response = await api.get(`/material-technical-documents/${row.id}/download`, { responseType: "blob" }); const url = URL.createObjectURL(response.data), link = document.createElement("a"); link.href = url; link.download = row.file_name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { this.error(e); } }, async history(row) { try { this.historyItems = (await api.get(`/material-technical-documents/${row.id}/history`, { params: { page: 1, page_size: 100 } })).data.items; this.historyVisible = true; } catch (e) { this.error(e); } }, async remove(row) { try { await this.$confirm(`删除 ${row.document_no} V${row.version} 草稿？`, "删除确认", { type: "warning" }); await api.delete(`/material-technical-documents/${row.id}`); await this.load(); this.$message.success("技术资料草稿已删除"); } catch (e) { if (e !== "cancel") this.error(e); } }
  }
};
</script>

<style scoped>
.material-head,.toolbar,.pager{display:flex;align-items:center;justify-content:space-between;gap:12px}.material-head{margin-bottom:15px}.material-head h3{margin:0 0 5px}.material-head p{margin:0;color:#7a8798}.eyebrow{font-size:11px;color:#2f6bff!important;letter-spacing:1.2px}.counts{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.counts button{border:1px solid #e6ebf2;background:#f8fafc;border-radius:9px;padding:12px 15px;text-align:left;cursor:pointer}.counts span{display:block;color:#7a8798;font-size:12px}.counts strong{font-size:23px;color:#29415c}.toolbar{justify-content:flex-start;margin-bottom:12px}.toolbar .el-input{width:250px}.toolbar .el-select{width:150px}.pager{margin-top:12px;color:#7a8798;font-size:13px}.tip{margin:4px 0 0;color:#8b97a8;font-size:12px}.review-note{margin-top:14px}.danger{color:#f56c6c}.el-table small{display:block;color:#9aa5b4}@media(max-width:900px){.counts{grid-template-columns:repeat(2,1fr)}.toolbar{flex-wrap:wrap}}
</style>
