<template>
 <div>
  <p>项目授权独立于采购分类授权。只读成员可查看获授权项目；计划编辑可调整任务，但不可修改项目预算、状态和档案。授权按日期及人员启用状态生效；管理员和采购经理保留管理权限。</p>
  <el-button type="primary" @click="open()">新增项目授权</el-button>
  <div class="table-toolbar"><el-select v-model="projectFilter" filterable clearable placeholder="全部项目" @change="page=1;load()"><el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id"/></el-select><el-select v-model="staffFilter" filterable clearable placeholder="全部人员" @change="page=1;load()"><el-option v-for="p in staff" :key="p.id" :label="p.name" :value="p.id"/></el-select></div>
  <el-table :data="items"><el-table-column prop="project" label="项目"/><el-table-column prop="staff" label="人员"/><el-table-column label="角色"><template slot-scope="s">{{s.row.role==='planner'?'计划编辑':'只读成员'}}</template></el-table-column><el-table-column prop="valid_from" label="开始"/><el-table-column prop="valid_to" label="结束"/><el-table-column label="当前有效"><template slot-scope="s">{{s.row.effective?'有效':'无效'}}</template></el-table-column><el-table-column label="操作"><template slot-scope="s"><el-button type="text" @click="open(s.row)">编辑</el-button><el-button type="text" @click="remove(s.row)">撤销</el-button></template></el-table-column></el-table><el-pagination :current-page.sync="page" :total="total" :page-size="10" layout="total,prev,pager,next" @current-change="load"/>
  <el-dialog title="项目人员授权" :visible.sync="visible" width="600px" append-to-body :close-on-click-modal="false"><el-form label-width="100px"><el-form-item label="项目"><el-select v-model="form.project_id" filterable><el-option v-for="p in projects" :key="p.id" :label="p.code+' '+p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="人员"><el-select v-model="form.staff_id" filterable><el-option v-for="p in staff" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="角色"><el-select v-model="form.role"><el-option label="只读成员" value="viewer"/><el-option label="计划编辑" value="planner"/></el-select></el-form-item><el-form-item label="有效期"><el-date-picker v-model="period" type="daterange" value-format="yyyy-MM-dd"/></el-form-item></el-form><span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存授权</el-button></span></el-dialog>
 </div>
</template>
<script>
import {api} from '../api/client';
export default {data:()=>({items:[],projects:[],staff:[],projectFilter:'',staffFilter:'',page:1,total:0,visible:false,saving:false,id:'',form:{},period:[]}),async created(){await this.load();for(const [path,key] of [['projects','projects'],['staff-users','staff']]){try{for(let page=1;page<=100;page++){const r=(await api.get('/'+path,{params:{page,page_size:100}})).data;this[key].push(...r.items);if(page*100>=r.total)break;}}catch(e){this.error(e);}}},methods:{error(e){const d=e.response?.data?.detail;this.$message.error(typeof d==='string'?d:'请检查人员、项目及有效期');},async load(){try{const r=(await api.get('/project-grants',{params:{project_id:this.projectFilter,staff_id:this.staffFilter,page:this.page}})).data;this.items=r.items;this.total=r.total;}catch(e){this.error(e);}},open(row){this.id=row?.id||'';this.form=row?{project_id:row.project_id,staff_id:row.staff_id,role:row.role}:{project_id:'',staff_id:'',role:'viewer'};this.period=row?[row.valid_from,row.valid_to]:[];this.visible=true;},async save(){if(!this.form.project_id||!this.form.staff_id||this.period?.length!==2)return this.$message.warning('请完整选择项目、人员和有效期');this.saving=true;try{const data={...this.form,valid_from:this.period[0],valid_to:this.period[1]};await (this.id?api.put('/project-grants/'+this.id,data):api.post('/project-grants',data));this.visible=false;await this.load();}catch(e){this.error(e);}finally{this.saving=false;}},async remove(row){try{await this.$confirm('撤销此项目人员授权？','确认');await api.delete('/project-grants/'+row.id);await this.load();}catch(e){if(e!=='cancel')this.error(e);}}}};
</script>
