<template>
 <div>
  <p>含税订单分摊口径：草稿／待审批为拟采购，审批后为承诺金额；取消订单单列，不计入承诺。不是实际成本或现金支出。</p>
  <div class="metric-grid"><div v-for="m in metrics" :key="m[0]" class="metric-card"><span>{{m[0]}} · {{data.project&&data.project.currency}}</span><strong>{{Number(m[1]||0).toFixed(2)}}</strong></div></div>
  <el-alert v-if="data.over_budget" title="采购承诺金额超过项目总预算，请核查分摊和预算。" type="warning" :closable="false"/>
  <el-button @click="open()">关联采购明细</el-button><el-button @click="load">刷新</el-button>
  <el-table :data="(data.rows||[]).slice((page-1)*10,page*10)"><el-table-column prop="order_no" label="订单号"/><el-table-column prop="material_code" label="物料"/><el-table-column label="任务"><template slot-scope="s">{{((data.project.tasks||[]).find(t=>t.id===s.row.task_id)||{}).name||'项目级'}}</template></el-table-column><el-table-column prop="quantity" label="分摊数量"/><el-table-column prop="amount" label="含税金额"/><el-table-column label="口径"><template slot-scope="s">{{labels[s.row.category]}}</template></el-table-column><el-table-column label="操作"><template slot-scope="s"><el-button type="text" @click="open(s.row)">编辑</el-button><el-button type="text" @click="remove(s.row)">移除</el-button></template></el-table-column></el-table><el-pagination :current-page.sync="page" :total="(data.rows||[]).length" :page-size="10" layout="total,prev,pager,next"/>
  <el-dialog title="采购明细分摊" :visible.sync="visible" width="850px" append-to-body :close-on-click-modal="false">
   <template v-if="!editing"><el-input v-model="keyword" placeholder="订单号或物料编码" @keyup.enter.native="linePage=1;search()"/><el-button @click="linePage=1;search()">搜索订单行</el-button><el-table :data="lines"><el-table-column prop="order_no" label="订单"/><el-table-column prop="material_code" label="物料"/><el-table-column prop="quantity" label="订单数量"/><el-table-column prop="allocated" label="已分摊"/><el-table-column label="选择"><template slot-scope="s"><el-radio v-model="form.line_id" :label="s.row.id">{{s.row.id}}</el-radio></template></el-table-column></el-table><el-pagination :current-page.sync="linePage" :total="lineTotal" :page-size="10" layout="total,prev,pager,next" @current-change="search"/></template>
   <el-form label-width="100px"><el-form-item label="分摊数量"><el-input-number v-model="form.quantity" :min="0.0001" :precision="4"/></el-form-item><el-form-item label="关联任务"><el-select v-model="form.task_id" clearable placeholder="项目级"><el-option v-for="t in (data.project&&data.project.tasks)||[]" :key="t.id" :value="t.id" :label="t.name"/></el-select></el-form-item></el-form>
   <span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存分摊</el-button></span>
  </el-dialog>
 </div>
</template>
<script>
import {api} from '../api/client';
export default {props:{projectId:String},data:()=>({data:{},page:1,visible:false,editing:'',keyword:'',linePage:1,lineTotal:0,lines:[],form:{line_id:null,task_id:'',quantity:1},busy:false,labels:{draft:'拟采购',committed:'采购承诺',cancelled:'已取消'}}),computed:{metrics(){return [['项目总预算',this.data.project?.budget],['拟采购',this.data.draft],['采购承诺',this.data.committed],['取消订单分摊',this.data.cancelled]];}},created(){this.load();},methods:{error(e){const d=e.response?.data?.detail;this.$message.error(typeof d==='string'?d:'分摊操作失败');},async load(){try{this.data=(await api.get('/project-costs/'+this.projectId)).data;}catch(e){this.error(e);}},open(row){this.editing=row?.id||'';this.form=row?{line_id:row.line_id,task_id:row.task_id,quantity:row.quantity}:{line_id:null,task_id:'',quantity:1};this.visible=true;this.linePage=1;this.search();},async search(){try{const r=(await api.get('/project-costs/lines',{params:{currency:this.data.project.currency,keyword:this.keyword,page:this.linePage}})).data;this.lines=r.items;this.lineTotal=r.total;}catch(e){this.error(e);}},async save(){if(!this.form.line_id)return this.$message.warning('请选择订单行');this.busy=true;try{const path='/project-costs/'+this.projectId;await (this.editing?api.put(path+'/'+this.editing,this.form):api.post(path,this.form));this.visible=false;await this.load();this.$message.success('分摊已保存');}catch(e){this.error(e);}finally{this.busy=false;}},async remove(row){try{await this.$confirm('解除此采购明细分摊？','确认');await api.delete('/project-costs/'+this.projectId+'/'+row.id);await this.load();}catch(e){if(e!=='cancel')this.error(e);}}}};
</script>
