<template>
  <div><p>指标来自外部批次反馈，按供应商＋物料编码统计；单元格显示中位数，点击查看原始值、正态分析与箱线图。没有数据时不填默认分数。</p><div class="table-toolbar"><el-input v-model.trim="material" placeholder="按物料编码查询" clearable/><el-checkbox v-model="includeDemo" @change="search">包含模拟数据</el-checkbox><el-button @click="search">查询指标</el-button></div><el-alert v-if="includeDemo" type="warning" title="包含模拟数据，仅供演示；正式分析请取消勾选。" :closable="false"/><el-table :data="items" v-loading="loading" border><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="material_code" label="物料编码"/><el-table-column prop="batches" label="批次" width="70"/><el-table-column v-for="(label,key) in labels" :key="key" :label="label"><template slot-scope="s"><el-button type="text" :disabled="!s.row.metrics[key].n" @click="inspect(s.row,key)">{{num(s.row.metrics[key].median)}} <small>({{s.row.metrics[key].n}}批)</small></el-button></template></el-table-column></el-table><Pager :page="pagination" @change="changePage" @size="changeSize"/>
    <el-dialog title="物料供货指标统计分析" custom-class="analysis-dialog" :visible.sync="visible" width="1080px" append-to-body><template v-if="analysis.statistics"><h3>{{selected.supplier_name}} / {{selected.material_code}} / {{analysis.label}}</h3><p>有效样本 {{analysis.statistics.n}}，缺失 {{analysis.missing_count}}，模拟 {{analysis.demo_count}}；中位数 {{num(analysis.statistics.median)}}，均值 {{num(analysis.statistics.mean)}}，标准差 {{num(analysis.statistics.std)}}</p><el-alert :title="analysis.statistics.normality+'；Shapiro-Wilk p='+num(analysis.statistics.p_value)" type="info" :closable="false"/><div class="chart-grid"><div class="chart-card"><h3>实际分布与正态参考曲线</h3><AnalysisChart :option="normalChart"/></div><div class="chart-card"><h3>中位数与四分位数箱线图</h3><AnalysisChart :option="medianChart"/></div></div><AnalysisChart :option="qqChart"/><el-table :data="analysis.items" border><el-table-column prop="external_id" label="来源批次"/><el-table-column prop="source_system" label="来源系统"/><el-table-column prop="record_date" label="日期"/><el-table-column label="指标值"><template slot-scope="s">{{num(s.row.value)}}</template></el-table-column><el-table-column prop="received_quantity" label="收货数"/><el-table-column prop="inspected_quantity" label="检验数"/><el-table-column prop="accepted_quantity" label="合格数"/><el-table-column prop="on_time_quantity" label="准时数"/><el-table-column prop="response_hours" label="响应小时"/></el-table><Pager :page="detailPage" @change="detailChange" @size="detailSize"/></template><span slot="footer"><el-button @click="visible=false">关闭</el-button></span></el-dialog>
  </div>
</template>
<script>
import {api} from '../api/client';import Pager from './Pager.vue';import AnalysisChart from './AnalysisChart.vue';
export default {components:{Pager,AnalysisChart},props:{supplierCode:{type:String,default:''}},data:()=>({labels:{quality:'质量合格率(%)',delivery:'准时交付率(%)',rework:'返工率(%)',response:'响应时长(小时)'},material:'',includeDemo:false,items:[],loading:false,pagination:{page:1,page_size:10,total:0},detailPage:{page:1,page_size:10,total:0},visible:false,selected:{},metric:'quality',analysis:{}}),created(){this.load();},computed:{normalChart(){const s=this.analysis.statistics;return {tooltip:{trigger:'axis'},legend:{data:['实际密度','正态参考']},xAxis:{type:'value',scale:true},yAxis:{type:'value',name:'密度'},series:[{name:'实际密度',type:'bar',barWidth:20,data:s.histogram},{name:'正态参考',type:'line',showSymbol:false,data:s.normal_curve}]};},medianChart(){return {tooltip:{trigger:'item'},xAxis:{type:'category',data:['最小 / Q1 / 中位数 / Q3 / 最大']},yAxis:{type:'value',scale:true},series:[{type:'boxplot',data:[this.analysis.statistics.box]}]};},qqChart(){return {title:{text:'正态 Q-Q 图'},tooltip:{},xAxis:{type:'value',name:'理论正态分位'},yAxis:{type:'value',name:'实际分位',scale:true},series:[{type:'scatter',data:this.analysis.statistics.qq}]};}},methods:{num(v){return v===null||v===undefined?'—':Number(v).toFixed(3);},async load(){this.loading=true;try{const r=(await api.get('/supplier-metrics',{params:{...this.pagination,supplier_code:this.supplierCode,material_code:this.material,include_demo:this.includeDemo}})).data;this.items=r.items;this.pagination.total=r.total;}catch(e){this.$message.error('指标读取失败');}finally{this.loading=false;}},search(){this.pagination.page=1;this.load();},changePage(p){this.pagination.page=p;this.load();},changeSize(n){this.pagination.page_size=n;this.search();},inspect(row,metric){this.selected=row;this.metric=metric;this.detailPage.page=1;this.loadDetail();},async loadDetail(){try{this.analysis=(await api.get('/supplier-metrics/statistics',{params:{...this.detailPage,supplier_code:this.selected.supplier_code,material_code:this.selected.material_code,metric:this.metric,include_demo:this.includeDemo}})).data;this.detailPage.total=this.analysis.total;this.visible=true;}catch(e){this.$message.error('统计分析失败');}},detailChange(p){this.detailPage.page=p;this.loadDetail();},detailSize(n){this.detailPage.page=1;this.detailPage.page_size=n;this.loadDetail();}}};
</script>
