<template>
 <section class="toc-weights">
  <h2>TOC核心：指标系数、影响权重与验证</h2>
  <el-select v-model="material" @change="samplePage=1"><el-option v-for="code in Object.keys(models)" :key="code" :value="code" :label="code"/></el-select>
  <el-tag style="margin-left:12px" :type="model.usable?'success':'warning'">{{ model.usable?'通过历史回测（非DOE）':'待补数 / 待复核' }}{{ model.demo_count?' · 模拟演示':'' }}</el-tag>
  <p>按同物料、币种和单位合并供应商批次建模，确保比较口径一致。目标是单位合格交付综合成本，不将权重误当成采购报价的因果影响。</p>
  <div class="toc-process"><div v-for="(step,i) in steps" :key="step.title"><b>{{ i+1 }} · {{ step.title }}</b><p>{{step.text}}</p></div></div>
  <div class="toc-formula"><p>已实现成本 y = [含税货款 + 物流 + 返工 + 延期 + 其他 − 退款] ÷ 合格交付数量</p><p>zⱼ = [clip(xⱼ, P₁, P₉₉) − μⱼ] / σⱼ； ŷ = α + Σ bⱼzⱼ； βⱼ = bⱼ / σⱼ</p><p><strong>影响权重 wⱼ = |bⱼ| / Σ|bₖ|，Σwⱼ = 1（100%）</strong>。不把 β 强制归一化，不把 w 直接乘以人民币成本。b 为一个标准差变化对应的预测成本变化。</p></div>
  <el-alert v-for="warning in model.warnings || []" :key="warning" :title="warning" type="warning" :closable="false"/>
  <div class="metric-grid"><div class="metric-card"><span>原始 / 可建模批次</span><strong>{{ model.raw_n || 0 }} / {{ model.n || 0 }}</strong></div><div class="metric-card"><span>训练 / 时间留出</span><strong>{{ model.validation ? model.validation.train_n+' / '+model.validation.test_n : '—' }}</strong></div><div class="metric-card"><span>留出 MAE / 基线 MAE</span><strong>{{num(model.validation && model.validation.mae)}} / {{num(model.validation && model.validation.baseline_mae)}}</strong></div><div class="metric-card"><span>留出 R² / 权重合计</span><strong>{{num(model.validation && model.validation.r_squared)}} / {{model.weight_sum===undefined?'—':(model.weight_sum*100).toFixed(1)+'%'}}</strong></div></div>
  <div class="chart-grid"><div class="chart-card"><h3>指标权重（和为100%）</h3><ExplainableChart :option="weightChart" title="多指标影响权重" interpretation="扇区表示各指标对模型预测的相对贡献，全部权重合计100%。扇区越大表示该指标在当前数据和模型中更重要，但不代表因果关系。" principle="先对指标标准化，再以标准化回归系数绝对值除以全部绝对值之和得到权重，从而避免量纲直接影响比较。"/></div><div class="chart-card"><h3>原始回归系数与方向</h3><ExplainableChart :option="coefficientChart" title="原始回归系数与方向" interpretation="正系数表示指标增加时预测综合成本上升，负系数表示下降；不同指标量纲不同，不能只按柱长比较重要性。" principle="原始系数是在其他指标保持不变时，一个原始单位变化对应的预测成本变化；相关性与共线性会影响稳定性。"/><p>各系数量纲不同，不能按原始数值大小直接比较重要性。</p></div></div>
  <el-table :data="model.weights || []" border><el-table-column prop="label" label="指标" min-width="150"/><el-table-column label="原始系数 β"><template slot-scope="s">{{num(s.row.coefficient,5)}}</template></el-table-column><el-table-column label="标准化系数 b"><template slot-scope="s">{{num(s.row.standardized,5)}}</template></el-table-column><el-table-column label="权重"><template slot-scope="s">{{pct(s.row.weight)}}</template></el-table-column><el-table-column label="95%稳定区间" min-width="160"><template slot-scope="s">{{pct(s.row.ci_low)}} ~ {{pct(s.row.ci_high)}}</template></el-table-column><el-table-column label="置换后MAE增量" min-width="150"><template slot-scope="s">{{num(s.row.permutation_mae)}}</template></el-table-column><el-table-column label="训练范围" min-width="170"><template slot-scope="s">{{num(s.row.min)}} ~ {{num(s.row.max)}} {{s.row.unit}}</template></el-table-column></el-table>
  <p v-if="model.model">模型截距（原始量纲）：{{num(model.intercept,5)}}；岭惩罚 λ={{model.validation.alpha}}；训练日期早于 {{model.validation.cutoff}}；模型版本 {{model.version}}；数据指纹 {{model.fingerprint}}。</p>
  <p>稳定区间：按业务日期成组重采样60次、固定已选λ，展示2.5%至97.5%分位数，用于敏感性观察，不能当作因果或显著性证明。置换增量≤0表示留出集没有支持该项独立预测价值；强相关指标的单项解释尤其需要谨慎。</p>
  <el-collapse v-model="panels">
   <el-collapse-item title="采集字段、来源系统和处理规则" name="collection"><el-table :data="collection" border><el-table-column prop="field" label="需采集字段" min-width="220"/><el-table-column prop="source" label="来源系统" width="150"/><el-table-column prop="rule" label="采集 / 分析规则" min-width="400"/></el-table><el-table :data="model.features || []"><el-table-column prop="label" label="建模指标"/><el-table-column prop="rule" label="计算公式" min-width="400"/></el-table><TocCollection @imported="$emit('refresh')"/></el-collapse-item>
   <el-collapse-item title="数据质量、缺失、异常与标准化" name="quality"><div class="chart-grid"><ExplainableChart :option="qualityChart" title="建模数据质量构成" interpretation="图中对比可建模批次和因缺失、口径不一致等原因被拒绝的批次。可建模占比过低时，任何系数和排名都应谨慎使用。" principle="系统按完整字段、时间口径、单位币种、合格数量及费用确认规则逐批校验，只把满足同一统计口径的数据送入模型。"/><el-table :data="model.weights || []"><el-table-column prop="label" label="指标"/><el-table-column label="训练均值 μ"><template slot-scope="s">{{num(s.row.mean)}}</template></el-table-column><el-table-column label="训练标准差 σ"><template slot-scope="s">{{num(s.row.std)}}</template></el-table-column></el-table></div><p>缺失不补0；至少3个此前完整指标批次才能生成滞后中位数。训练集输入P1/P99缩尾，仅限制数值极端影响，不删除原始数据；目标成本不缩尾。训练集被缩尾批次 {{model.outlier_rows || 0}} 条。零合格交付不能计算单位成本，作为独立风险事件保留，近期出现时禁止供应商预测。</p><p>同一业务批次由来源系统+供应商+批次ID去重。必须采集指标实际可用日期 metrics_available_date，缺失时禁止多元预测定标；生产对接还需保存报价时点、质检完成、费用确认时间，避免迟到反馈造成信息泄漏。</p></el-collapse-item>
   <el-collapse-item title="相关性、指标敏感性曲线与权重解释" name="correlation"><ExplainableChart :option="correlationChart" title="指标相关性热力图" interpretation="颜色和数字表示两个指标的相关方向与强度，绝对值接近1说明高度同步。高度相关会使单项系数不稳定，需要合并指标或增加数据。" principle="采用样本相关系数衡量线性共同变化；相关不等于因果，强共线性会增加回归系数方差。"/><el-select v-model="featureIndex"><el-option v-for="(f,i) in model.features || []" :key="f.key" :label="f.label" :value="i"/></el-select><ExplainableChart :option="curveChart" title="指标敏感性曲线" interpretation="曲线展示选中指标在训练范围内变化时，预测综合成本如何变化，其他指标固定在训练均值。不要外推到训练范围之外。" principle="把其他特征固定，仅改变一个特征并代入已拟合模型形成条件响应曲线；它是模型敏感性说明，不是单因素因果试验。"/><p>曲线表示其他指标固定为训练均值时的预测变化，不是各指标独立散点回归，也不代表改变该指标必然产生此收益。|相关系数|≥0.9或指标恒定时，展示诊断但禁止回归定标。</p></el-collapse-item>
   <el-collapse-item title="时间留出验证、残差与原始批次" name="validation"><div class="chart-grid"><ExplainableChart :option="fitChart" title="留出集实际成本与预测成本" interpretation="散点越接近45度方向，预测越接近实际；系统性偏离提示模型偏差，离群点提示特殊批次或数据问题。" principle="按时间留出后，用较早批次训练、较晚批次验证，避免用未来数据解释过去。MAE与R²需同时优于基线才具备预测参考价值。"/><ExplainableChart :option="residualChart" title="预测残差诊断" interpretation="残差应在零线两侧随机分布。趋势、弧形或漏斗形分别可能提示时间漂移、非线性或异方差。" principle="残差为实际综合成本减去预测成本，用于检查模型假设和遗漏结构；残差小不等于因果成立。"/></div><p>训练期内部按50%/65%/80%滚动日期切分，从λ=0.1、1、10、100选择MAE最小者；最后约20%日期完全留出。MAE必须优于训练目标中位数基线且R²>0，候选指标不得超出训练适用范围。</p><p>残差Shapiro p={{num(model.residual_diagnostics && model.residual_diagnostics.shapiro_p,4)}}。检查的是误差分布；自变量无需正态。p≥0.05不证明正态，p&lt;0.05也不自动否定预测用途，还需检查异方差、趋势和异常点。</p><el-table :data="(model.samples || []).slice((samplePage-1)*10,samplePage*10)" max-height="350"><el-table-column prop="batch" label="批次" min-width="170"/><el-table-column prop="date" label="日期"/><el-table-column prop="supplier" label="供应商"/><el-table-column label="实际成本"><template slot-scope="s">{{num(s.row.y)}}</template></el-table-column><el-table-column label="预测成本"><template slot-scope="s">{{num(s.row.prediction)}}</template></el-table-column><el-table-column label="残差"><template slot-scope="s">{{num(s.row.residual)}}</template></el-table-column></el-table><el-pagination :current-page.sync="samplePage" :page-size="10" :total="(model.samples || []).length" layout="total,prev,pager,next"/></el-collapse-item>
  </el-collapse>
  <p class="muted">统计依据：<a href="https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd141.htm" target="_blank" rel="noopener">NIST线性回归</a> · <a href="https://www.itl.nist.gov/div898/software/dataplot/refman1/auxillar/regrdiag.htm" target="_blank" rel="noopener">回归诊断</a> · <a href="https://scikit-learn.org/stable/modules/permutation_importance.html" target="_blank" rel="noopener">留出集置换重要性</a>。权重为本数据和本模型下的关联解释，不是市场报价因果权重。</p>
</section>
</template>
<script>
import ExplainableChart from './ExplainableChart.vue';
import TocCollection from './TocCollection.vue';
export default {
 components:{ExplainableChart,TocCollection},props:{models:{type:Object,default:()=>({})}},data:()=>({material:'',featureIndex:0,samplePage:1,panels:['collection'],steps:[{title:'采集与对齐',text:'同物料/币种/单位；保留来源与日期'},{title:'构造历史特征',text:'此前最近5批中位数；至少3批'},{title:'清洗与标准化',text:'仅训练集缩尾、均值与标准差'},{title:'多元岭回归',text:'时间滚动验证选择λ与系数'},{title:'解释与验证',text:'100%权重、稳定区间、残差'},{title:'定标适用检查',text:'验证通过且不外推；否则统一回退'}],collection:[{field:'supplier_code / material_code / external_id / record_date / metrics_available_date',source:'ERP / WMS',rule:'供应商与物料主数据编码；唯一实际业务批次；业务日期不可在未来；重复批次不能跨系统重复计入。'},{field:'unit / currency / unit_price / tax_rate / logistics_cost',source:'ERP / 财务 / WMS',rule:'统一币种、计量单位、税口径；物流为整批费用，先除收货数量；不自动换汇。'},{field:'received_quantity / on_time_quantity',source:'WMS / ERP',rule:'根据订单承诺交期判断准时数量；延期率=1−准时/实收，不用人工主档评分。'},{field:'inspected_quantity / accepted_quantity / rework_quantity',source:'MES / QMS',rule:'同一批次全量质检；合格和返工各不超过检验量；返工不等同报废。'},{field:'response_hours',source:'SRM / 工单系统',rule:'请求到首次有效回复的小时数，保留工单证据；缺失不能按0。'},{field:'rework_cost / delay_cost / other_cost / credit / costs_confirmed',source:'财务 / QMS / ERP',rule:'确认实际金额，关联费用凭证；避免物流、返工重复入账；退款不能超过费用总额。'}]}),watch:{models:{immediate:true,handler(){if(!this.models[this.material])this.material=Object.keys(this.models)[0]||'';}}},computed:{
 model(){return this.models[this.material]||{};},
 weightChart(){return {tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['35%','65%'],data:(this.model.weights||[]).map(w=>({name:w.label,value:w.weight*100})),label:{formatter:'{b}\n{d}%'}}]};},
 coefficientChart(){const w=this.model.weights||[];return {tooltip:{trigger:'axis'},grid:{left:120,right:30,bottom:30},xAxis:{type:'value'},yAxis:{type:'category',data:w.map(r=>r.label)},series:[{type:'bar',data:w.map(r=>r.coefficient)}]};},
 qualityChart(){return {tooltip:{trigger:'item'},series:[{type:'pie',data:[{name:'可建模',value:this.model.n||0},...Object.entries(this.model.rejected||{}).map(([name,value])=>({name,value}))]}]};},
 correlationChart(){const labels=(this.model.features||[]).map(f=>f.label);return {tooltip:{},grid:{left:120,bottom:90},xAxis:{type:'category',data:labels,axisLabel:{rotate:20}},yAxis:{type:'category',data:labels},visualMap:{min:-1,max:1,calculable:true,orient:'horizontal',bottom:0,left:'center'},series:[{type:'heatmap',data:(this.model.correlation||[]).flatMap((row,i)=>row.map((v,j)=>[j,i,v])),label:{show:true,formatter:p=>Number(p.value[2]).toFixed(2)}}]};},
 curveChart(){const c=(this.model.curves||[])[this.featureIndex];return {tooltip:{trigger:'axis'},xAxis:{type:'value',name:c?.name,scale:true},yAxis:{type:'value',name:'预测TOC',scale:true},series:[{type:'line',data:c?.data||[]}]};},
 fitChart(){return {title:{text:'留出：实际 vs 预测',textStyle:{fontSize:14}},tooltip:{},xAxis:{type:'value',name:'实际',scale:true},yAxis:{type:'value',name:'预测',scale:true},series:[{type:'scatter',data:(this.model.samples||[]).map(s=>[s.y,s.prediction])}]};},
 residualChart(){return {title:{text:'残差 vs 预测',textStyle:{fontSize:14}},tooltip:{},xAxis:{type:'value',name:'预测',scale:true},yAxis:{type:'value',name:'实际−预测',scale:true},series:[{type:'scatter',data:(this.model.samples||[]).map(s=>[s.prediction,s.residual]),markLine:{data:[{yAxis:0}],silent:true}}]};}
 },methods:{num(v,n=2){return v===null||v===undefined?'—':Number(v).toFixed(n);},pct(v){return this.num(v*100)+'%';}}
};
</script>
