<template>
  <div>
    <div class="page-heading"><div><p class="eyebrow">系统集成</p><h1>数据与 API 接入</h1><p>连接 ERP、MES、SRM、QMS、WMS 与自定义业务接口，统一纳入采购决策数据底座。</p></div><el-button type="primary" @click="openCreate">新建系统连接器</el-button></div>
    <el-button style="margin-bottom:16px" @click="feedbackConnector=null;feedbackVisible=true">反馈接入说明 / 模板 / 数据</el-button><el-dialog title="供货反馈数据接入" :visible.sync="feedbackVisible" width="1100px"><FeedbackIntegration v-if="feedbackVisible" :connector="feedbackConnector" @refresh="load"/><span slot="footer"><el-button @click="feedbackVisible=false">关闭</el-button></span></el-dialog>
    <el-button style="margin-bottom:16px" @click="testUrl='';testVisible=true">API 接口测试</el-button><el-dialog title="API 接口测试与 JSON 预览" :visible.sync="testVisible" width="850px" :close-on-click-modal="false" :close-on-press-escape="!testBusy" :show-close="!testBusy"><ApiTester v-if="testVisible" :url="testUrl" @busy="testBusy=$event"/><span slot="footer"><el-button :disabled="testBusy" @click="testVisible=false">关闭</el-button></span></el-dialog><div class="connector-note"><strong>安全原则</strong><span>供货反馈通过专用令牌接收主动推送，令牌只保存哈希；第三方数据须先转换为统一字段。</span></div>
    <div class="table-toolbar"><el-input v-model.trim="keyword" clearable placeholder="搜索连接器名称或服务地址" @keyup.enter.native="search" @clear="search"/><el-button icon="el-icon-search" @click="search">查询</el-button><el-button @click="keyword='';search()">重置</el-button></div>
    <el-table v-loading="loading" :data="connectors" class="data-table" empty-text="尚未配置系统连接器"><el-table-column prop="name" label="连接器名称" min-width="200"/><el-table-column prop="connector_type" label="类型" width="150"><template slot-scope="scope"><el-tag type="info">{{ typeName(scope.row.connector_type) }}</el-tag></template></el-table-column><el-table-column prop="base_url" label="服务地址" min-width="220" show-overflow-tooltip/><el-table-column prop="sync_mode" label="同步方式" width="130"><template slot-scope="scope">{{ syncName(scope.row.sync_mode) }}</template></el-table-column><el-table-column prop="status" label="状态" width="110"><template slot-scope="scope"><el-tag :type="scope.row.status==='active'?'success':'info'">{{ statusName(scope.row.status) }}</el-tag></template></el-table-column><el-table-column prop="created_by" label="配置人" width="140"/><el-table-column label="操作" width="300"><template slot-scope="scope"><el-button v-if="scope.row.connector_type!=='mineru'" type="text" @click="feedbackConnector=scope.row;feedbackVisible=true">供货反馈接入</el-button><el-button type="text" @click="testConnector(scope.row)">接口测试</el-button><el-button type="text" @click="openEdit(scope.row)">编辑</el-button><el-button type="text" class="danger-link" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table>
    <div class="pagination-row"><span>共 {{pagination.total}} 条</span><el-pagination background layout="sizes, prev, pager, next" :page-sizes="[10,20,50]" :current-page="pagination.page" :page-size="pagination.page_size" :total="pagination.total" @current-change="changePage" @size-change="changeSize"/></div>
    <el-dialog :title="editingId?'编辑系统连接器':'新建系统连接器'" :visible.sync="dialogVisible" width="580px" :close-on-click-modal="false"><el-form ref="form" :model="form" :rules="rules" label-width="110px"><el-form-item label="连接器名称" prop="name"><el-input v-model.trim="form.name" placeholder="例如：SAP ERP 生产环境"/></el-form-item><el-form-item label="系统类型"><el-select v-model="form.connector_type" style="width:100%"><el-option label="ERP" value="erp"/><el-option label="MES" value="mes"/><el-option label="SRM" value="srm"/><el-option label="QMS" value="qms"/><el-option label="WMS" value="wms"/><el-option label="MinerU PDF解析" value="mineru"/><el-option label="自定义 API" value="custom_api"/></el-select></el-form-item><el-alert v-if="$route.query.setup==='toc-api'" title="TOC接入：保存后启用连接器，点击供货反馈接入生成令牌，按字段字典向本系统推送JSON；服务地址仅登记来源，不会自动拉取。" type="info" :closable="false"/><el-alert v-if="form.connector_type==='mineru'" title="填写自托管MinerU服务根地址或/file_parse地址。保存后再次编辑并设为已启用；项目PDF导入将优先调用。通用接口测试仅允许公网HTTPS，自托管内网服务请通过实际PDF导入验收。" type="info" :closable="false"/><el-form-item label="服务地址"><el-input v-model.trim="form.base_url" :placeholder="form.connector_type==='mineru'?'http://mineru:8000 或 https://mineru.example.com':'https://api.example.com'"/></el-form-item><el-form-item label="同步方式"><el-radio-group v-model="form.sync_mode"><el-radio label="manual">手动</el-radio><el-radio label="scheduled">定时</el-radio><el-radio label="webhook">事件推送</el-radio></el-radio-group></el-form-item><el-form-item v-if="editingId" label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="待启用" value="draft"/><el-option label="已启用" value="active"/><el-option label="已停用" value="disabled"/><el-option label="异常" value="error"/></el-select></el-form-item></el-form><span slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存连接器</el-button></span></el-dialog>
  </div>
</template>
<script>
import ApiTester from "../components/ApiTester.vue";
import FeedbackIntegration from "../components/FeedbackIntegration.vue";
import { createConnector, deleteConnector, fetchConnectors, updateConnector } from "../api/client";
const emptyForm=()=>({name:"",connector_type:"erp",base_url:"",sync_mode:"manual",status:"draft"});
export default {components:{FeedbackIntegration,ApiTester},data:()=>({testVisible:false,testBusy:false,testUrl:"",feedbackVisible:false,feedbackConnector:null,connectors:[],dialogVisible:false,saving:false,loading:false,editingId:"",keyword:"",form:emptyForm(),pagination:{page:1,page_size:10,total:0},rules:{name:[{required:true,message:"请输入连接器名称",trigger:"blur"}]}}),created(){this.load();if(['toc-api','mineru'].includes(this.$route.query.setup))this.openCreate();},methods:{typeName(type){return {erp:"ERP",mes:"MES",srm:"SRM",qms:"QMS",wms:"WMS",mineru:"MinerU PDF解析",custom_api:"自定义 API"}[type]||type;},syncName(mode){return {manual:"手动",scheduled:"定时同步",webhook:"事件推送"}[mode]||mode;},statusName(value){return {draft:"待启用",active:"已启用",disabled:"已停用",error:"异常"}[value]||value;},testConnector(item){const base=item.base_url.replace(/\/file_parse\/?$/,"").replace(/\/$/,"");this.testUrl=base+(item.connector_type==='mineru'?'/health':'');this.testVisible=true;},async load(){this.loading=true;try{const result=await fetchConnectors({page:this.pagination.page,page_size:this.pagination.page_size,keyword:this.keyword});this.connectors=result.items;this.pagination.total=result.total;}catch(_){this.$message.error("连接器加载失败");}finally{this.loading=false;}},search(){this.pagination.page=1;this.load();},changePage(page){this.pagination.page=page;this.load();},changeSize(size){this.pagination.page_size=size;this.pagination.page=1;this.load();},openCreate(){this.editingId="";this.form=emptyForm();if(this.$route.query.setup==='toc-api'){this.form.sync_mode='webhook';this.form.name='TOC 供货反馈接口';}if(this.$route.query.setup==='mineru'){this.form.connector_type='mineru';this.form.name='MinerU PDF解析服务';this.form.sync_mode='manual';}this.dialogVisible=true;this.$nextTick(()=>this.$refs.form&&this.$refs.form.clearValidate());},openEdit(item){this.editingId=item.id;this.form={name:item.name,connector_type:item.connector_type,base_url:item.base_url,sync_mode:item.sync_mode,status:item.status};this.dialogVisible=true;},save(){this.$refs.form.validate(async valid=>{if(!valid)return;if(this.form.connector_type==='mineru'&&!/^https?:\/\//.test(this.form.base_url)){this.$message.error("MinerU服务地址必须以http://或https://开头");return;}this.saving=true;try{if(this.editingId)await updateConnector(this.editingId,this.form);else await createConnector(this.form);this.$message.success("连接器已保存");this.dialogVisible=false;await this.load();}catch(error){this.$message.error(error.response&&error.response.data&&error.response.data.detail||"连接器保存失败");}finally{this.saving=false;}});},async remove(item){try{await this.$confirm(`确定删除连接器 ${item.name} 吗？`,"删除确认",{type:"warning"});await deleteConnector(item.id);this.$message.success("连接器已删除");await this.load();}catch(error){if(error!=="cancel")this.$message.error("连接器删除失败");}}}};
</script>
