<template>
  <div>
    <div class="page-heading"><div><p class="eyebrow">智能分析 · TOC</p><h1>物料采购成本分析</h1><p>从物料编号追踪订单、报价、比价快照与供应商交付记录，修正采购成本。</p></div><router-link class="primary-action" to="/rfqs">查看询价与回标</router-link></div>
    <div class="table-toolbar"><el-input v-model.trim="code" placeholder="请输入物料编号" @keyup.enter.native="search"/><el-select v-model="currency" style="width:110px"><el-option v-for="c in ['CNY','USD','EUR','JPY','GBP']" :key="c" :value="c" :label="c"/></el-select><el-button type="primary" :loading="loading" @click="search">查询采购历史</el-button></div>
    <template v-if="summary">
      <div class="connector-note"><strong>核算口径</strong><span>{{ summary.formula }}<br/>货款按订单计价；“已发生”仅指人工确认的附加费用，并非发票结算核验。无费用凭证、无质检或无合格品时不宣称实际单位成本。退货数量不自动视为退款，需填写已确认退款金额。</span></div>
      <div class="metric-grid"><div v-for="metric in metrics" :key="metric.key" class="metric-card"><span>{{ metric.name }}</span><strong>{{ summary.counts[metric.key] }}</strong><small>{{ metric.note }}</small></div></div>
      <div class="chart-grid"><div class="chart-card"><div class="chart-title"><strong>供应商单位成本对照</strong><span>{{ summary.currency }} · 同单位比较</span></div><div ref="costChart" class="chart-box"/></div><div class="chart-card"><div class="chart-title"><strong>供应商交付质量</strong><span>按已检数量计算</span></div><div ref="qualityChart" class="chart-box"/></div></div>
      <el-table :data="summary.suppliers" class="data-table" empty-text="暂无该物料供货记录"><el-table-column prop="supplier_name" label="供应商" min-width="160"/><el-table-column prop="unit" label="单位" width="70"/><el-table-column prop="batches" label="供货批次" width="90"/><el-table-column prop="eligible_batches" label="可核算批次" width="100"/><el-table-column label="原始含税单价" width="130"><template slot-scope="s">{{ money(s.row.base_unit_cost) }}</template></el-table-column><el-table-column label="修正合格品成本" width="140"><template slot-scope="s">{{ money(s.row.corrected_unit_cost) }}</template></el-table-column><el-table-column label="费用已确认批次" width="140"><template slot-scope="s">{{ s.row.confirmed_batches }} / {{ s.row.eligible_batches }}</template></el-table-column><el-table-column label="合格率" width="100"><template slot-scope="s">{{ money(s.row.quality_rate) }}%</template></el-table-column></el-table>
      <div class="list-heading"><h2>采购链路历史</h2><p>历史业务单据在原业务模块维护；成本修正保留审计记录。比价快照仅记录本功能上线后的比价结果。</p></div>
      <el-tabs v-model="active" @tab-click="changeTab"><el-tab-pane name="orders" label="采购订单历史"/><el-tab-pane name="receipts" label="采购 / 供货历史与成本修正"/><el-tab-pane name="quotations" label="供应商报价"/><el-tab-pane name="comparisons" label="比价历史"/></el-tabs>
      <div v-if="active!=='comparisons'" class="table-toolbar"><el-select v-model="supplierFilter" clearable filterable placeholder="筛选供应商供货历史" @change="changeTab"><el-option v-for="s in summary.supplier_options" :key="s.id" :value="s.id" :label="`${s.name} [${s.id}]`"/></el-select></div>
      <div v-if="active==='quotations' || active==='comparisons'" class="table-toolbar"><el-input-number v-model="quantity" :min="0.0001" :precision="4"/><el-button type="primary" :loading="comparing" @click="compare">按此数量进行 TOC 比价并留存</el-button></div>
      <el-table v-loading="historyLoading" :data="rows" class="data-table" :key="active" empty-text="当前物料、币种暂无历史记录">
        <el-table-column v-if="active==='comparisons'" type="expand"><template slot-scope="s"><p>{{ s.row.result ? s.row.result.methodology : "" }}</p><el-table :data="s.row.result ? s.row.result.items : []"><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="quotation_no" label="报价单"/><el-table-column prop="tco_amount" label="TOC总成本"/><el-table-column prop="evaluation_score" label="综合分"/></el-table></template></el-table-column>
        <el-table-column label="日期" width="165"><template slot-scope="s">{{ String(s.row.date || '').slice(0,19).replace('T',' ') }}</template></el-table-column>
        <template v-if="active==='orders'"><el-table-column prop="order_no" label="订单编号" width="150"/><el-table-column prop="supplier_name" label="供应商" min-width="160"/><el-table-column prop="status" label="状态" width="110"/><el-table-column prop="quantity" label="数量" width="90"/><el-table-column prop="unit" label="单位" width="70"/><el-table-column prop="unit_price" label="未税单价" width="110"/><el-table-column label="含税金额" width="130"><template slot-scope="s">{{ money(s.row.amount) }}</template></el-table-column></template>
        <template v-else-if="active==='quotations'"><el-table-column prop="quotation_no" label="报价编号" width="150"/><el-table-column prop="supplier_name" label="供应商" min-width="150"/><el-table-column prop="quantity" label="报价数量" width="100"/><el-table-column prop="unit_price" label="未税单价" width="100"/><el-table-column prop="delivery_days" label="交期/天" width="85"/><el-table-column label="报价TOC" width="120"><template slot-scope="s">{{ money(s.row.tco) }}</template></el-table-column></template>
        <template v-else-if="active==='receipts'"><el-table-column type="expand"><template slot-scope="s"><p>订单 {{ s.row.order_no }} · {{ s.row.note }}</p><p>返工数量：{{ s.row.rework_quantity == null ? '未知' : s.row.rework_quantity }}；退货数量：{{ s.row.returned_quantity }}；延期天数：{{ s.row.late_days == null ? '未知' : s.row.late_days }}</p><p>物流 {{ s.row.logistics }} + 返工 {{ s.row.rework }} + 延期 {{ s.row.delay }} + 其他 {{ s.row.other }} − 退款/索赔 {{ s.row.credit }}</p><p>凭证/依据：{{ s.row.evidence }}</p></template></el-table-column><el-table-column prop="receipt_no" label="收货批次" width="145"/><el-table-column prop="supplier_name" label="供应商" min-width="150"/><el-table-column prop="received_quantity" label="收到数量" width="100"/><el-table-column prop="accepted_quantity" label="合格数量" width="100"/><el-table-column prop="rejected_quantity" label="不合格数量" width="100"/><el-table-column label="修正单位成本" width="130"><template slot-scope="s">{{ money(s.row.corrected_unit_cost) }}</template></el-table-column><el-table-column label="附加费用依据" width="130"><template slot-scope="s">{{ basisName(s.row.basis) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="150"><template slot-scope="s"><el-button type="text" :disabled="!s.row.eligible" @click="edit(s.row)">修正费用</el-button><el-button type="text" class="danger-link" :disabled="s.row.basis==='unconfirmed'" @click="clearAdjustment(s.row)">清除</el-button></template></el-table-column></template>
        <template v-else><el-table-column prop="quantity" label="比价数量" width="130"/><el-table-column prop="currency" label="币种" width="90"/><el-table-column prop="created_by" label="操作人"/><el-table-column label="参与报价数"><template slot-scope="s">{{ s.row.result ? s.row.result.items.length : 0 }}</template></el-table-column></template>
      </el-table>
      <div class="pagination-row"><span>共 {{ total }} 条</span><el-pagination :current-page="page" :page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="sizes,prev,pager,next" @current-change="changePage" @size-change="changeSize"/></div>
      <div v-if="active==='receipts'" class="chart-card"><div class="chart-title"><strong>当前页供货批次成本走势</strong><span>按收货日期 · {{ summary.currency }}</span></div><div ref="batchChart" class="chart-box"/></div>
    </template>
    <el-empty v-else description="输入物料编号，查询真实采购与供应商履约记录"/>
    <el-dialog title="修正该收货批次的附加费用" :visible.sync="dialog" width="650px" :close-on-click-modal="false"><el-form label-width="140px"><p>货款按原订单含税价格计价，本操作不会修改原订单或财务账。费用单位：{{ summary ? summary.currency : currency }}</p><el-form-item v-for="field in costFields" :key="field.key" :label="field.name"><el-input-number v-model="form[field.key]" :min="0" :precision="2"/></el-form-item><el-form-item label="费用依据"><el-select v-model="form.basis"><el-option label="已发生（有凭证）" value="actual"/><el-option label="估算（待确认）" value="estimated"/></el-select></el-form-item><el-form-item label="凭证编号 / 依据" required><el-input v-model.trim="form.evidence" type="textarea" maxlength="1000" placeholder="填写费用凭证编号及说明，或估算方法"/></el-form-item></el-form><span slot="footer"><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存并重算</el-button></span></el-dialog>
  </div>
</template>
<script>
import * as echarts from "echarts";
import { api, compareQuotations } from "../api/client";
export default {
  data: () => ({ code: "", currency: "CNY", selectedCode: "", supplierFilter: "", selectedCurrency: "CNY", summary: null, rows: [], total: 0, page: 1, pageSize: 10, active: "orders", quantity: 1, loading: false, historyLoading: false, comparing: false, saving: false, dialog: false, receiptId: "", form: {}, metrics: [{key:"orders",name:"订单明细",note:"采购历史订单行"},{key:"receipts",name:"供货批次",note:"含草稿，核算排除草稿"},{key:"quotations",name:"供应商报价",note:"该物料的报价明细"},{key:"comparisons",name:"比价快照",note:"上线后留存"}], costFields: [{key:"logistics",name:"物流成本"},{key:"rework",name:"返工成本"},{key:"delay",name:"延期损失"},{key:"other",name:"其他附加费用"},{key:"credit",name:"已确认退款 / 索赔"}] }),
  mounted() { this.charts=[]; window.addEventListener("resize",this.resize); },
  beforeDestroy() { window.removeEventListener("resize",this.resize); this.dispose(); },
  methods: {
    money(v) { return v == null ? "—" : Number(v).toFixed(2); }, basisName(v) { return {actual:"已发生（人工确认）",estimated:"估算",unconfirmed:"未确认"}[v] || v; },
    dispose() { (this.charts||[]).forEach(c=>c.dispose()); this.charts=[]; }, resize() { (this.charts||[]).forEach(c=>c.resize()); },
    async search() { if(!this.code) return this.$message.warning("请输入物料编号"); this.loading=true; this.dispose(); this.summary=null; this.rows=[]; this.selectedCode=this.code; this.selectedCurrency=this.currency; this.page=1; this.supplierFilter=""; try { await this.refresh(); } catch(e) { this.$message.error(e.response?.data?.detail || "查询失败"); } finally { this.loading=false; } },
    async refresh() { const {data}=await api.get("/material-costs/summary",{params:{material_code:this.selectedCode,currency:this.selectedCurrency}}); this.summary=data; await this.loadHistory(); },
    async loadHistory() { this.rows=[]; this.historyLoading=true; try { const {data}=await api.get(`/material-costs/history/${this.active}`,{params:{material_code:this.selectedCode,currency:this.selectedCurrency,page:this.page,page_size:this.pageSize,supplier_id:this.supplierFilter}}); this.rows=data.items;this.total=data.total;this.$nextTick(this.render); } catch(e) { this.rows=[];this.total=0;this.$message.error("历史记录加载失败"); } finally { this.historyLoading=false; } },
    changeTab() { this.page=1;this.loadHistory(); },changePage(p) {this.page=p;this.loadHistory();},changeSize(s) {this.pageSize=s;this.page=1;this.loadHistory();},
    async compare() { this.comparing=true;try { const result=await compareQuotations({material_code:this.selectedCode,currency:this.selectedCurrency,quantity:this.quantity});this.$message[result.items.length?'success':'info'](result.items.length?'比价结果已留存':'没有可比较的报价');this.rows=[];this.active='comparisons';this.page=1;await this.refresh(); } catch(e) {this.$message.error(e.response?.data?.detail || '比价失败');} finally {this.comparing=false;} },
    edit(row) { this.receiptId=row.id;this.form={basis:row.basis==='actual'?'actual':'estimated',evidence:row.basis==='unconfirmed'?'':row.evidence};this.costFields.forEach(f=>{this.form[f.key]=Number(row[f.key]);});this.dialog=true; },
    async save() { if(!this.form.evidence || this.form.evidence.length<2) return this.$message.warning('请填写费用凭证或估算依据');this.saving=true;try {await api.put(`/material-costs/receipts/${this.receiptId}/adjustment`,this.form);this.dialog=false;this.$message.success('成本已修正并留存审计');await this.refresh();}catch(e){const detail=e.response?.data?.detail;this.$message.error(typeof detail==='string'?detail:'费用保存失败，请检查数值和凭证');}finally{this.saving=false;} },
    async clearAdjustment(row) {try {await this.$confirm('清除附加费用并恢复未确认状态？审计记录仍保留。','确认清除');await api.delete(`/material-costs/receipts/${row.id}/adjustment`);await this.refresh();}catch(e){if(e!=='cancel' && e!=='close')this.$message.error(e.response?.data?.detail || '清除失败');}},
    render() {if(!this.summary || !this.$refs.costChart)return;this.dispose();const rows=this.summary.suppliers;const labels=rows.map(r=>`${r.supplier_name} [${r.supplier_id}] /${r.unit}`);const common={tooltip:{trigger:'axis'},legend:{bottom:0},grid:{left:60,right:20,top:30,bottom:95},xAxis:{type:'category',data:labels,axisLabel:{rotate:15,overflow:'truncate',width:100}},yAxis:{type:'value'}};
      const cost=echarts.init(this.$refs.costChart);cost.setOption({...common,series:[{name:'收货含税单价',type:'bar',data:rows.map(r=>r.base_unit_cost),itemStyle:{color:'#65a7ff'}},{name:'修正合格品成本',type:'bar',data:rows.map(r=>r.corrected_unit_cost),itemStyle:{color:'#2878ff'}}]});
      const quality=echarts.init(this.$refs.qualityChart);quality.setOption({...common,yAxis:{type:'value',max:100},series:[{name:'合格率 %',type:'bar',data:rows.map(r=>r.quality_rate),itemStyle:{color:'#54b99c'}}]});this.charts=[cost,quality];
      if(this.active==='receipts' && this.$refs.batchChart){const batch=echarts.init(this.$refs.batchChart);const items=[...this.rows].reverse();batch.setOption({tooltip:{trigger:'axis'},legend:{bottom:0},grid:{left:65,right:25,top:30,bottom:70},xAxis:{type:'category',data:items.map(r=>`${r.date} ${r.supplier_name} ${r.receipt_no}`),axisLabel:{overflow:'truncate',width:120}},yAxis:{type:'value'},series:[{name:'原始单价',type:'line',data:items.map(r=>r.base_unit_cost)},{name:'修正合格品成本',type:'line',connectNulls:false,data:items.map(r=>r.corrected_unit_cost)}]});this.charts.push(batch);}}
  }
};
</script>
