<template>
  <div>
    <div class="page-heading"><div><p class="eyebrow">组织、账号、角色与业务范围</p><h1>系统人员管理</h1><p>统一维护人员档案、学习登录账号、采购分类权限与项目授权。</p></div><el-button v-if="!['project','learning'].includes(active)" type="primary" @click="openCreate">新增{{ activeLabel }}</el-button></div>
    <div class="permission-note"><strong>权限规则</strong><span>人员档案是采购、项目和教学账号的共同主数据；学习账号只用于考试与课件，不会自动获得采购业务权限。</span></div>
    <el-tabs v-model="active" type="card" @tab-click="changeTab"><el-tab-pane label="人员配置" name="staff"/><el-tab-pane label="学习登录账号" name="learning"/><el-tab-pane label="采购员分类授权" name="authorizations"/><el-tab-pane label="项目人员授权" name="project"/></el-tabs><ProjectGrants v-if="active==='project'"/><LearningAccounts v-if="active==='learning'"/><template v-if="!['project','learning'].includes(active)">
    <div class="table-toolbar" v-if="active==='staff'"><el-input v-model.trim="keyword" clearable placeholder="搜索编号、姓名、部门" @keyup.enter.native="search" @clear="search"/><el-select v-model="status" clearable placeholder="全部状态" @change="search"><el-option label="启用" value="active"/><el-option label="停用" value="disabled"/></el-select><el-button icon="el-icon-search" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
    <el-table v-if="active==='staff'" v-loading="loading" :data="items" class="data-table" empty-text="暂无人员"><el-table-column prop="user_code" label="人员编号" width="130"/><el-table-column prop="name" label="姓名" width="120"/><el-table-column prop="department" label="部门" min-width="130"/><el-table-column prop="title" label="岗位" min-width="130"/><el-table-column label="系统角色" width="130"><template slot-scope="s"><el-tag>{{ roleName(s.row.role) }}</el-tag></template></el-table-column><el-table-column prop="email" label="邮箱" min-width="190"/><el-table-column label="状态" width="90"><template slot-scope="s"><el-tag :type="s.row.status==='active'?'success':'info'">{{ s.row.status==='active'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template slot-scope="s"><el-button type="text" @click="edit(s.row)">编辑</el-button><el-button type="text" class="danger-link" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
    <el-table v-else v-loading="loading" :data="items" class="data-table" empty-text="暂无采购授权"><el-table-column prop="buyer_name" label="采购员" width="140"/><el-table-column prop="category_code" label="分类编码" width="145"/><el-table-column prop="category_name" label="负责分类" min-width="220"/><el-table-column label="授权级别" width="100"><template slot-scope="s">{{ s.row.category_level }}级</template></el-table-column><el-table-column prop="valid_from" label="生效日期" width="120"/><el-table-column prop="valid_to" label="失效日期" width="120"/><el-table-column label="当前有效" width="100"><template slot-scope="s"><el-tag :type="s.row.effective?'success':'info'">{{ s.row.effective?'有效':'无效' }}</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template slot-scope="s"><el-button type="text" @click="edit(s.row)">编辑</el-button><el-button type="text" class="danger-link" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
    <div class="pagination-row"><span>共 {{ pagination.total }} 条</span><el-pagination background layout="sizes, prev, pager, next" :page-sizes="[10,20,50]" :current-page="pagination.page" :page-size="pagination.page_size" :total="pagination.total" @current-change="changePage" @size-change="changeSize"/></div>

    </template><el-dialog :title="`${editingId?'编辑':'新增'}${activeLabel}`" :visible.sync="dialogVisible" width="620px" :close-on-click-modal="false"><el-form ref="form" :model="form" :rules="rules" label-width="105px">
      <template v-if="active==='staff'"><el-row :gutter="16"><el-col :span="12"><el-form-item label="人员编号" prop="user_code"><el-input v-model.trim="form.user_code" :disabled="!!editingId"/></el-form-item></el-col><el-col :span="12"><el-form-item label="姓名" prop="name"><el-input v-model.trim="form.name"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="部门"><el-input v-model.trim="form.department"/></el-form-item></el-col><el-col :span="12"><el-form-item label="岗位"><el-input v-model.trim="form.title"/></el-form-item></el-col></el-row><el-form-item label="邮箱"><el-input v-model.trim="form.email"/></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="系统角色"><el-select v-model="form.role" style="width:100%"><el-option v-for="r in roles" :key="r.value" :label="r.label" :value="r.value"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="启用" value="active"/><el-option label="停用" value="disabled"/></el-select></el-form-item></el-col></el-row></template>
      <template v-else><el-form-item label="采购员" prop="buyer_id"><el-select v-model="form.buyer_id" filterable :disabled="!!editingId" style="width:100%"><el-option v-for="b in buyers" :key="b.id" :label="`${b.user_code} ${b.name}`" :value="b.id"/></el-select></el-form-item><el-form-item label="物料分类" prop="category_id"><el-select v-model="form.category_id" filterable :disabled="!!editingId" style="width:100%"><el-option v-for="c in categories" :key="c.id" :label="`${c.code} ${c.path_name}（${c.level}级）`" :value="c.id"/></el-select></el-form-item><el-form-item label="有效期" prop="period"><el-date-picker v-model="form.period" type="daterange" value-format="yyyy-MM-dd" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" style="width:100%"/></el-form-item><el-form-item v-if="editingId" label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="启用" value="active"/><el-option label="停用" value="disabled"/></el-select></el-form-item></template>
    </el-form><span slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></span></el-dialog>
  </div>
</template>

<script>
import ProjectGrants from "../components/ProjectGrants.vue";
import LearningAccounts from "../components/LearningAccounts.vue";
import { createBuyerAuthorization, createStaffUser, deleteBuyerAuthorization, deleteStaffUser, fetchBuyerAuthorizations, fetchMaterialCategoryTree, fetchStaffUsers, updateBuyerAuthorization, updateStaffUser } from "../api/client";
const staffForm = () => ({ user_code: "BUY-", name: "", email: "", department: "采购部", title: "采购员", role: "buyer", status: "active" });
const authForm = () => ({ buyer_id: "", category_id: "", period: [], status: "active" });
export default {
  components:{ProjectGrants,LearningAccounts},
  data: () => ({ active: "staff", items: [], buyers: [], categories: [], keyword: "", status: "", loading: false, saving: false, dialogVisible: false, editingId: "", form: staffForm(), pagination: { page: 1, page_size: 10, total: 0 }, roles: [{ value: "admin", label: "管理员" }, { value: "procurement_manager", label: "采购经理" }, { value: "buyer", label: "采购员" }, { value: "analyst", label: "分析员" }, { value: "auditor", label: "审计员" }, { value: "instructor", label: "讲师" }, { value: "student", label: "学员" }], rules: { user_code: [{ required: true, message: "请输入人员编号", trigger: "blur" }], name: [{ required: true, message: "请输入姓名", trigger: "blur" }], buyer_id: [{ required: true, message: "请选择采购员", trigger: "change" }], category_id: [{ required: true, message: "请选择物料分类", trigger: "change" }], period: [{ type: "array", required: true, len: 2, message: "请选择完整有效期", trigger: "change" }] } }),
  computed: { activeLabel() { return this.active === "staff" ? "人员" : "采购授权"; } },
  created() { this.loadReferences(); this.load(); },
  methods: {
    roleName(v) { return { admin: "管理员", procurement_manager: "采购经理", buyer: "采购员", analyst: "分析员", auditor: "审计员", instructor: "讲师", student: "学员" }[v] || v; },
    async loadReferences() { const [staff, categories] = await Promise.all([fetchStaffUsers({ page: 1, page_size: 100, status: "active" }), fetchMaterialCategoryTree()]); this.buyers = staff.items.filter(item => item.role === "buyer"); this.categories = categories.filter(item => item.active); },
    async load() { if(['project','learning'].includes(this.active))return; this.loading = true; try { const result = this.active === "staff" ? await fetchStaffUsers({ page: this.pagination.page, page_size: this.pagination.page_size, keyword: this.keyword, status: this.status }) : await fetchBuyerAuthorizations({ page: this.pagination.page, page_size: this.pagination.page_size }); this.items = result.items; this.pagination.total = result.total; } catch (e) { this.$message.error("人员权限加载失败"); } finally { this.loading = false; } },
    changeTab() { this.pagination.page = 1; this.keyword = ""; this.status = ""; this.load(); }, search() { this.pagination.page = 1; this.load(); }, reset() { this.keyword = ""; this.status = ""; this.search(); }, changePage(p) { this.pagination.page = p; this.load(); }, changeSize(s) { this.pagination.page_size = s; this.pagination.page = 1; this.load(); },
    openCreate() { this.editingId = ""; this.form = this.active === "staff" ? staffForm() : authForm(); this.dialogVisible = true; },
    edit(row) { this.editingId = row.id; this.form = this.active === "staff" ? { ...row } : { ...row, period: [row.valid_from, row.valid_to] }; this.dialogVisible = true; },
    async save() { this.$refs.form.validate(async valid => { if (!valid) return; this.saving = true; try { if (this.active === "staff") { const payload = { name: this.form.name, email: this.form.email, department: this.form.department, title: this.form.title, role: this.form.role, status: this.form.status }; if (this.editingId) await updateStaffUser(this.editingId, payload); else await createStaffUser({ user_code: this.form.user_code, ...payload }); } else { const payload = { valid_from: this.form.period[0], valid_to: this.form.period[1] }; if (this.editingId) await updateBuyerAuthorization(this.editingId, { ...payload, status: this.form.status }); else await createBuyerAuthorization({ buyer_id: this.form.buyer_id, category_id: this.form.category_id, ...payload }); } this.$message.success(`${this.activeLabel}已保存`); this.dialogVisible = false; await this.loadReferences(); await this.load(); } catch (e) { this.$message.error(e.response && e.response.data && e.response.data.detail || "保存失败"); } finally { this.saving = false; } }); },
    async remove(row) { try { await this.$confirm(`确定删除${this.activeLabel}吗？`, "删除确认", { type: "warning" }); if (this.active === "staff") await deleteStaffUser(row.id); else await deleteBuyerAuthorization(row.id); this.$message.success("删除成功"); await this.loadReferences(); await this.load(); } catch (e) { if (e !== "cancel") this.$message.error(e.response && e.response.data && e.response.data.detail || "删除失败"); } }
  }
};
</script>
