<template>
 <div>
  <div class="page-heading"><div><p class="eyebrow">节点跟踪 · 处理闭环</p><h1>项目通知</h1><p>执行中项目：任务／里程碑提前3个日历日提醒；含税采购承诺超过项目总预算时通知项目经理。</p></div><el-button type="primary" :loading="busy" @click="scan">检查项目节点</el-button></div>
  <el-alert title="Docker部署的项目扫描服务每60秒检查一次；本地开发需运行扫描服务或点击检查。邮件仅在确认后发送，任务完成或条件变化后提醒自动解除。" :closable="false"/>
  <div class="table-toolbar"><el-select v-model="state" clearable placeholder="全部状态" @change="page=1;load()"><el-option v-for="(label,key) in states" :key="key" :value="key" :label="label"/></el-select><el-button @click="load">刷新</el-button><router-link to="/mail-settings">邮件设置</router-link></div>
  <el-table :data="items" v-loading="loading"><el-table-column prop="subject" label="通知" min-width="200"/><el-table-column prop="body" label="内容" min-width="260" show-overflow-tooltip/><el-table-column label="处理状态"><template slot-scope="s">{{states[s.row.state]}}</template></el-table-column><el-table-column label="邮件状态"><template slot-scope="s">{{mail[s.row.mail_status]}}</template></el-table-column><el-table-column prop="recipient" label="已发送目标"/><el-table-column prop="created_at" label="生成时间" min-width="180"/><el-table-column label="操作" width="260"><template slot-scope="s"><el-button type="text" @click="$router.push({path:'/projects',query:{project:s.row.project_id}})">查看项目</el-button><el-button v-if="s.row.state==='open'" type="text" :disabled="busy" @click="ack(s.row)">确认收到</el-button><el-button v-if="s.row.state!=='resolved'&&s.row.mail_status==='not_sent'" type="text" :disabled="busy" @click="send(s.row)">发送邮件</el-button><el-tooltip v-if="s.row.error" :content="s.row.error"><el-tag type="warning">需核查</el-tag></el-tooltip></template></el-table-column></el-table>
  <el-pagination :current-page.sync="page" :total="total" :page-size="10" layout="total,prev,pager,next" @current-change="load"/>
 </div>
</template>
<script>
import {api} from '../api/client';
export default {data:()=>({items:[],state:'',page:1,total:0,busy:false,loading:false,states:{open:'待处理',acknowledged:'已确认',resolved:'已解除'},mail:{not_sent:'未发送',sending:'发送中',sent:'已发送',uncertain:'结果未确认'}}),created(){this.load();},methods:{error(e){this.$message.error(e.response?.data?.detail||'操作失败');},async load(){this.loading=true;try{const r=(await api.get('/project-notifications',{params:{state:this.state,page:this.page}})).data;this.items=r.items;this.total=r.total;}catch(e){this.error(e);}finally{this.loading=false;}},async scan(){this.busy=true;try{const r=(await api.post('/project-notifications/scan')).data;this.$message.success('新增'+r.inserted+'条提醒');await this.load();}catch(e){this.error(e);}finally{this.busy=false;}},async ack(row){this.busy=true;try{await api.post('/project-notifications/'+row.id+'/acknowledge');await this.load();}catch(e){this.error(e);}finally{this.busy=false;}},async send(row){try{await this.$confirm(row.body+'\n将发送到任务负责人当前人员档案邮箱，是否继续？','确认发送邮件');this.busy=true;const r=(await api.post('/project-notifications/'+row.id+'/send',null,{timeout:60000})).data;if(r.mail_status==='sent')this.$message.success('邮件已发送');else this.$message.warning(r.error);await this.load();}catch(e){if(e!=='cancel')this.error(e);}finally{this.busy=false;}}}};
</script>
