<template><div v-loading="loading">
 <h1>备件采购需求计划</h1><p>分类策略 → 候选方案TOC → 保障约束 → 采购计划草稿。不建设仓库执行模块。</p>
 <el-alert title="阶段一：人工参数测算与草稿管理；尚未接入自动分类、回归训练、审批和采购申请转换。" type="info" :closable="false"/>
 <div style="margin:18px 0"><el-input v-model="keyword" placeholder="物料编码" style="width:240px" @keyup.enter.native="page=1;load()"/><el-button @click="page=1;load()">查询</el-button><el-button type="primary" @click="open()">新增计划草稿</el-button></div>
 <el-table :data="items" border><el-table-column prop="material_code" label="物料编码"/><el-table-column prop="abc" label="ABC"/><el-table-column prop="ved" label="VED"/><el-table-column prop="fsn" label="FSN"/><el-table-column prop="required_date" label="需求日期"/><el-table-column prop="analysis.recommended" label="推荐方案"/><el-table-column label="操作" width="180"><template slot-scope="s"><el-button type="text" @click="open(s.row)">编辑分析</el-button><el-button type="text" @click="remove(s.row)">删除草稿</el-button></template></el-table-column></el-table>
 <el-pagination :current-page="page" :page-size="10" :total="total" layout="total,prev,pager,next" @current-change="page=$event;load()"/>
 <el-dialog title="备件TOC计划草稿" :visible.sync="visible" width="94%" top="3vh" :close-on-click-modal="false">
  <el-form label-width="145px" size="small">
   <el-row><el-col :span="8"><el-form-item label="现有物料编码"><el-input v-model="form.material_code"/></el-form-item></el-col><el-col :span="8"><el-form-item label="币种"><el-input v-model="form.currency"/></el-form-item></el-col><el-col :span="8"><el-form-item label="TOC预算上限"><el-input-number v-model="form.budget" :min="0"/></el-form-item></el-col></el-row>
   <el-row><el-col v-for="key in ['abc','ved','fsn']" :key="key" :span="8"><el-form-item :label="key.toUpperCase()+' 分类'"><el-select v-model="form[key]"><el-option v-for="v in classes[key]" :key="v" :label="v" :value="v"/></el-select></el-form-item></el-col></el-row>
   <el-form-item label="分类依据"><el-input v-model="form.classification_reason" placeholder="价值、关键性、流动性评审依据，不能只填分类标签"/></el-form-item>
   <el-row><el-col v-for="c in ['v','e','d']" :key="c" :span="8"><el-form-item :label="c.toUpperCase()+'类风险上限 %'"><el-input-number v-model="form['risk_limit_'+c]" :min="0" :max="100"/></el-form-item></el-col></el-row><p>请填写经业务评审的分类保障策略，风险上限要求 V ≤ E ≤ D，无预置行业标准。</p>
   <el-row><el-col v-for="(label,key) in dateFields" :key="key" :span="8"><el-form-item :label="label"><el-date-picker v-model="form[key]" value-format="yyyy-MM-dd" type="date"/></el-form-item></el-col></el-row>
   <el-row><el-col v-for="(label,key) in quantityFields" :key="key" :span="6"><el-form-item :label="label"><el-input-number v-model="form[key]" :min="0" :precision="0"/></el-form-item></el-col></el-row>
   <el-form-item label="数据来源与说明"><el-input v-model="form.data_source" placeholder="库存/在途/需求数据来源及批次；仅使用需求日前有效数量"/></el-form-item>
  </el-form>
  <h3>候选方案 · 所有费用统一为规划期间的预期金额</h3><p>分别填写非重叠的费用。不得重复计入停机、应急及质量损失。每个方案须说明估算依据。</p>
  <el-table :data="form.scenarios" border max-height="300">
   <el-table-column label="方案" width="160"><template slot-scope="s"><el-input v-model="s.row.name" size="small"/></template></el-table-column>
   <el-table-column v-for="(label,key) in scenarioFields" :key="key" :label="label" width="160"><template slot-scope="s"><el-input-number v-model="s.row[key]" size="small" :min="0" :max="key==='risk_percent'?100:1000000000" :precision="key==='quantity'?0:2" style="width:140px"/></template></el-table-column>
   <el-table-column label="到货日期" width="180"><template slot-scope="s"><el-date-picker v-model="s.row.arrival" value-format="yyyy-MM-dd" size="small" style="width:155px"/></template></el-table-column>
   <el-table-column label="数据依据" width="220"><template slot-scope="s"><el-input v-model="s.row.evidence" size="small"/></template></el-table-column><el-table-column label="操作" width="70"><template slot-scope="s"><el-button type="text" :disabled="form.scenarios.length<=2" @click="form.scenarios.splice(s.$index,1)">移除</el-button></template></el-table-column>
  </el-table><el-button size="small" :disabled="form.scenarios.length>=30" @click="form.scenarios.push(scenario())">添加方案</el-button>
  <template v-if="analysis"><el-alert :title="dirty?'参数已修改，请重新测算。':('净采购需求：'+analysis.net_demand+'；推荐：'+(analysis.recommended||'没有满足约束的方案'))" :type="dirty?'warning':'info'" :closable="false"/><p v-for="w in analysis.warnings" :key="w">{{w}}</p><AnalysisChart :option="chart"/><el-table :data="analysis.scenarios" border><el-table-column prop="name" label="方案"/><el-table-column prop="toc" label="计划TOC"/><el-table-column label="约束检查"><template slot-scope="s">{{s.row.feasible?'满足约束':s.row.reasons.join('；')}}</template></el-table-column></el-table></template>
  <span slot="footer"><el-button @click="visible=false">关闭</el-button><el-button :loading="working" @click="calculate">重新测算</el-button><el-button type="primary" :loading="working" @click="save">重新测算并保存草稿</el-button></span>
 </el-dialog>
</div></template>
<script>
import {api} from '../api/client';
import AnalysisChart from '../components/AnalysisChart.vue';
const today=()=>new Date().toISOString().slice(0,10);
const scenario=()=>({name:'',quantity:0,unit_price:0,arrival:today(),fees:0,holding:0,quality_loss:0,downtime_loss:0,emergency_loss:0,obsolescence_loss:0,risk_percent:0,evidence:''});
const empty=()=>({material_code:'',abc:'B',ved:'E',fsn:'S',classification_reason:'',currency:'CNY',as_of:today(),required_date:today(),horizon_end:today(),demand:0,available:0,confirmed_inbound:0,reserve:0,budget:0,risk_limit_v:undefined,risk_limit_e:undefined,risk_limit_d:undefined,data_source:'',scenarios:[scenario(),scenario()],version:1});
export default {components:{AnalysisChart},data:()=>({items:[],total:0,page:1,keyword:'',loading:false,working:false,visible:false,form:empty(),analysis:null,snapshot:'',classes:{abc:['A','B','C'],ved:['V','E','D'],fsn:['F','S','N']},dateFields:{as_of:'数据时点',required_date:'需求日期',horizon_end:'规划期末'},quantityFields:{demand:'需求数量',available:'可用数量',confirmed_inbound:'确认在途',reserve:'期末储备'},scenarioFields:{quantity:'采购数量',unit_price:'单价',fees:'订货运输',holding:'持有成本',quality_loss:'质量损失',downtime_loss:'停机损失',emergency_loss:'应急增量',obsolescence_loss:'呆滞淘汰',risk_percent:'缺货风险 %'}}),computed:{dirty(){return this.snapshot!==JSON.stringify(this.form);},chart(){const rows=this.analysis?.scenarios||[];return {tooltip:{trigger:'axis'},legend:{type:'scroll'},grid:{left:70,right:25,bottom:50},xAxis:{type:'category',data:rows.map(r=>r.name)},yAxis:{type:'value',name:this.form.currency},series:Object.keys(rows[0]?.parts||{}).map(k=>({name:k,type:'bar',stack:'toc',data:rows.map(r=>r.parts[k])}))};}},created(){this.load();},methods:{scenario,error(e){const d=e.response?.data?.detail;this.$message.error(typeof d==='string'?d:Array.isArray(d)?d.map(x=>x.loc.slice(1).join('.')+': '+x.msg).join('；'):e.message);},async load(){this.loading=true;try{const r=(await api.get('/spare-plans',{params:{keyword:this.keyword,page:this.page,page_size:10}})).data;this.items=r.items;this.total=r.total;}catch(e){this.error(e);}finally{this.loading=false;}},open(row){this.form=row?JSON.parse(JSON.stringify(row)):empty();this.analysis=this.form.analysis||null;delete this.form.analysis;this.snapshot=JSON.stringify(this.form);this.visible=true;},async calculate(){this.working=true;try{this.analysis=(await api.post('/spare-plans/analyze',this.form)).data;this.snapshot=JSON.stringify(this.form);}catch(e){this.error(e);}finally{this.working=false;}},async save(){this.working=true;try{const r=(await (this.form.id?api.put('/spare-plans/'+this.form.id,this.form):api.post('/spare-plans',this.form))).data;this.open(r);await this.load();this.$message.success('已重新测算并保存草稿');}catch(e){this.error(e);}finally{this.working=false;}},async remove(row){try{await this.$confirm('删除该计划草稿？','确认');await api.delete('/spare-plans/'+row.id,{params:{version:row.version}});await this.load();}catch(e){if(e!=='cancel')this.error(e);}}}};
</script>
