<template>
  <div>
    <div class="page-heading"><div><p class="eyebrow">模块五 + 模块六</p><h1>备件采购策略</h1><p>把寻源、价格控制、紧急采购、差异化供应商与长尾策略固化为可审批、可追溯的采购决策。</p></div><el-button type="primary" @click="open()">新建策略</el-button></div>
    <div class="metric-grid"><div class="metric-card"><span>策略总数</span><strong>{{pagination.total}}</strong><small>OEM、国产、替代与再制造</small></div><div class="metric-card"><span>国产/替代策略</span><strong>{{alternativeCount}}</strong><small>降低原厂单一依赖</small></div><div class="metric-card"><span>紧急采购</span><strong>{{urgentCount}}</strong><small>须控制溢价并保留依据</small></div><div class="metric-card"><span>VMI/寄售</span><strong>{{vmiCount}}</strong><small>差异化供应协同</small></div></div>
    <el-alert title="决策顺序：可获得性与停机风险 → 技术等效性 → TOC综合成本 → 价格基准与溢价 → 供应模式；‘必须进口’和‘最低价’均不能单独构成结论。" type="info" :closable="false"/>
    <div style="margin-top:16px"><el-select v-model="analysisMaterial" filterable clearable placeholder="选择备件进行联合策略分析"><el-option v-for="m in materials" :key="m.code" :label="m.code+' · '+m.name" :value="m.code"/></el-select><p>点击物料编码查看数据完整性、四策略图表、风险四象限、矛盾和结论。</p></div><StrategyDecision :material="analysisMaterial" @close="analysisMaterial=''"/>
    <div class="strategy-grid">
      <div><strong>寻源与价格</strong><p>OEM、国产替代、等效件、再制造；记录历史价、平台价与谈判基准。</p></div><div><strong>紧急采购</strong><p>停机等级、授权通道、最高溢价、备用方案和事后复盘。</p></div><div><strong>差异化供应</strong><p>标准供货、寄售、VMI、框架协议；按关键性与消耗特征匹配。</p></div><div><strong>长尾治理</strong><p>低值极少使用件采用行业共享库存、平台采购或集中框架。</p></div>
    </div>
    <div class="table-toolbar"><el-input v-model.trim="keyword" clearable placeholder="策略名称或物料编码" @keyup.enter.native="search" @clear="search"/><el-select v-model="sourceMode" clearable placeholder="寻源方式" @change="search"><el-option v-for="o in sourceOptions" :key="o.value" :label="o.label" :value="o.value"/></el-select><el-select v-model="urgency" clearable placeholder="采购等级" @change="search"><el-option label="计划采购" value="planned"/><el-option label="紧急采购" value="urgent"/><el-option label="停机抢修" value="shutdown"/></el-select><el-button icon="el-icon-search" @click="search">查询</el-button></div>
    <el-table v-loading="loading" :data="items" class="data-table" empty-text="暂无备件采购策略">
      <el-table-column prop="name" label="策略名称" min-width="180"/><el-table-column label="物料编码" width="140"><template slot-scope="s"><el-button v-if="s.row.material_code" type="text" @click="analysisMaterial=s.row.material_code">{{s.row.material_code}}</el-button></template></el-table-column><el-table-column label="寻源方式" width="110"><template slot-scope="s">{{label(sourceOptions,s.row.source_mode)}}</template></el-table-column><el-table-column label="供应模式" width="110"><template slot-scope="s">{{label(modelOptions,s.row.supplier_model)}}</template></el-table-column><el-table-column label="紧急程度" width="100"><template slot-scope="s"><el-tag :type="s.row.urgency==='planned'?'success':'danger'">{{urgencyName(s.row.urgency)}}</el-tag></template></el-table-column><el-table-column prop="price_baseline" label="价格基准" width="110"/><el-table-column label="溢价上限" width="95"><template slot-scope="s">{{s.row.premium_limit}}%</template></el-table-column><el-table-column label="状态" width="90"><template slot-scope="s">{{statusName(s.row.decision_status)}}</template></el-table-column><el-table-column label="操作" width="125" fixed="right"><template slot-scope="s"><el-button type="text" @click="open(s.row)">编辑</el-button><el-button type="text" class="danger-link" @click="remove(s.row)">删除</el-button></template></el-table-column>
    </el-table>
    <div class="pagination-row"><span>共 {{pagination.total}} 条</span><el-pagination background layout="sizes, prev, pager, next" :page-sizes="[10,20,50]" :current-page="pagination.page" :page-size="pagination.page_size" :total="pagination.total" @current-change="changePage" @size-change="changeSize"/></div>
    <el-dialog :title="form.id?'编辑备件采购策略':'新建备件采购策略'" :visible.sync="visible" width="760px" :close-on-click-modal="false">
      <el-form ref="form" :model="form" :rules="rules" label-width="110px">
        <el-row :gutter="16"><el-col :span="12"><el-form-item label="策略名称" prop="name"><el-input v-model.trim="form.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="物料编码"><el-select v-model="form.material_code" filterable clearable style="width:100%"><el-option v-for="m in materials" :key="m.code" :label="`${m.code} · ${m.name}`" :value="m.code"/></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="16"><el-col :span="8"><el-form-item label="寻源方式"><el-select v-model="form.source_mode" style="width:100%"><el-option v-for="o in sourceOptions" :key="o.value" :label="o.label" :value="o.value"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="供应模式"><el-select v-model="form.supplier_model" style="width:100%"><el-option v-for="o in modelOptions" :key="o.value" :label="o.label" :value="o.value"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="紧急程度"><el-select v-model="form.urgency" style="width:100%"><el-option label="计划采购" value="planned"/><el-option label="紧急采购" value="urgent"/><el-option label="停机抢修" value="shutdown"/></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="16"><el-col :span="8"><el-form-item label="价格基准"><el-input-number v-model="form.price_baseline" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="溢价上限"><el-input-number v-model="form.premium_limit" :min="0" :max="500" :precision="2" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="目标交期"><el-input-number v-model="form.lead_time_days" :min="0" style="width:100%"/></el-form-item></el-col></el-row>
        <el-form-item label="决策状态"><el-radio-group v-model="form.decision_status"><el-radio-button label="draft">草稿</el-radio-button><el-radio-button label="reviewing">评审中</el-radio-button><el-radio-button label="approved">已批准</el-radio-button><el-radio-button label="retired">已停用</el-radio-button></el-radio-group></el-form-item>
        <el-form-item label="决策依据" prop="rationale"><el-input v-model="form.rationale" type="textarea" :rows="4" placeholder="记录技术等效性、价格基准、停机风险、TOC及供应约束"/></el-form-item><el-form-item label="备用方案"><el-input v-model="form.fallback_plan" type="textarea" :rows="3" placeholder="紧急采购或单一来源失效时的替代路径"/></el-form-item>
      </el-form><span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></span>
    </el-dialog>
  </div>
</template>
<script>
import {api} from '../api/client';
import StrategyDecision from '../components/StrategyDecision.vue';
const fresh=()=>({id:'',name:'',material_code:'',source_mode:'oem',supplier_model:'standard',urgency:'planned',price_baseline:0,premium_limit:0,lead_time_days:0,decision_status:'draft',rationale:'',fallback_plan:'',version:1});
export default {components:{StrategyDecision},data:()=>({analysisMaterial:'',items:[],materials:[],loading:false,saving:false,visible:false,keyword:'',sourceMode:'',urgency:'',form:fresh(),pagination:{page:1,page_size:10,total:0},sourceOptions:[{value:'oem',label:'原厂OEM'},{value:'domestic',label:'国产化'},{value:'alternative',label:'等效替代件'},{value:'remanufactured',label:'再制造件'},{value:'platform',label:'平台采购'},{value:'shared_stock',label:'共享库存'}],modelOptions:[{value:'standard',label:'标准供货'},{value:'consignment',label:'寄售'},{value:'vmi',label:'VMI'},{value:'framework',label:'框架协议'},{value:'platform',label:'平台协同'}],rules:{name:[{required:true,message:'请输入策略名称',trigger:'blur'}],rationale:[{required:true,message:'请填写可复核的决策依据',trigger:'blur'}]}}),computed:{alternativeCount(){return this.items.filter(r=>['domestic','alternative','remanufactured'].includes(r.source_mode)).length;},urgentCount(){return this.items.filter(r=>r.urgency!=='planned').length;},vmiCount(){return this.items.filter(r=>['vmi','consignment'].includes(r.supplier_model)).length;}},created(){this.load();this.loadMaterials();},methods:{label(options,value){return options.find(o=>o.value===value)?.label||value;},urgencyName(v){return {planned:'计划采购',urgent:'紧急采购',shutdown:'停机抢修'}[v]||v;},statusName(v){return {draft:'草稿',reviewing:'评审中',approved:'已批准',retired:'已停用'}[v]||v;},error(e){this.$message.error(e.response?.data?.detail||e.message||'操作失败');},async load(){this.loading=true;try{const r=(await api.get('/spare-strategies',{params:{keyword:this.keyword,source_mode:this.sourceMode,urgency:this.urgency,...this.pagination}})).data;this.items=r.items;this.pagination.total=r.total;}catch(e){this.error(e);}finally{this.loading=false;}},async loadMaterials(){try{this.materials=(await api.get('/materials',{params:{material_type:'spare',page:1,page_size:100}})).data.items;}catch(e){this.error(e);}},search(){this.pagination.page=1;this.load();},changePage(v){this.pagination.page=v;this.load();},changeSize(v){this.pagination.page_size=v;this.pagination.page=1;this.load();},open(row){this.form=row?{...row,price_baseline:Number(row.price_baseline),premium_limit:Number(row.premium_limit)}:fresh();this.visible=true;},save(){this.$refs.form.validate(async ok=>{if(!ok)return;this.saving=true;try{if(this.form.id)await api.put('/spare-strategies/'+this.form.id,this.form);else await api.post('/spare-strategies',this.form);this.$message.success('备件采购策略已保存');this.visible=false;await this.load();}catch(e){this.error(e);}finally{this.saving=false;}});},async remove(row){try{await this.$confirm('删除该策略？','确认');await api.delete('/spare-strategies/'+row.id,{params:{version:row.version}});await this.load();this.$message.success('已删除');}catch(e){if(e!=='cancel')this.error(e);}}}};
</script>
