<template>
  <div><div class="page-heading"><div><h2>供应商账号</h2><p>供应商使用独立登录门户，只能查看受邀询价和自己的报价。密码请通过安全渠道告知。</p><p>供应商登录网址：{{portalUrl}}</p><a :href="portalUrl" target="_blank" rel="noopener">打开供应商登录门户 ↗</a></div><el-button type="primary" @click="open()">新增供应商账号</el-button></div>
    <ListFilters :only-resources="['supplier-accounts']" @query="pagination.page=1;load()"/><el-table :data="items" v-loading="loading"><el-table-column label="供应商"><template slot-scope="s">{{supplierName(s.row.supplier_id)}}</template></el-table-column><el-table-column prop="username" label="登录名"/><el-table-column label="状态"><template slot-scope="s"><el-tag :type="s.row.active?'success':'info'">{{s.row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作"><template slot-scope="s"><el-button type="text" @click="open(s.row)">编辑 / 重置密码</el-button></template></el-table-column></el-table>
    <Pager :page="pagination" @change="changePage" @size="changeSize"/>
    <el-dialog title="供应商登录账号" :visible.sync="visible" width="560px" append-to-body><el-form label-width="120px"><el-form-item label="供应商"><el-select v-model="form.supplier_id" filterable :disabled="!!form.id" style="width:100%"><el-option v-for="s in suppliers" :key="s.id" :label="s.code+' · '+s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="登录名"><el-input v-model.trim="form.username" /></el-form-item><el-form-item label="密码"><el-input v-model="form.password" show-password placeholder="至少12位；已有账号留空不改" autocomplete="new-password"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.active" /></el-form-item></el-form><span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></span></el-dialog>
  </div>
</template>
<script>
import ListFilters from '../components/ListFilters.vue';
import {api} from '../api/client';import Pager from '../components/Pager.vue';
export default {components:{ListFilters,Pager},data:()=>({portalUrl:"",items:[],suppliers:[],pagination:{page:1,page_size:10,total:0},form:{},visible:false,loading:false,saving:false}),async created(){if(this.$store.state.user.role!=="admin")return;const portal=(await api.get("/supplier-accounts/portal")).data;this.portalUrl=new URL(portal.url,window.location.origin).href;await this.load();let page=1;do{const r=(await api.get('/suppliers',{params:{page,page_size:100,unfiltered:true}})).data;this.suppliers.push(...r.items);if(this.suppliers.length>=r.total)break;page++;}while(page<100);},methods:{supplierName(id){return this.suppliers.find(s=>s.id===id)?.name||id;},async load(){this.loading=true;try{const r=(await api.get('/supplier-accounts',{params:this.pagination})).data;this.items=r.items;this.pagination.total=r.total;}catch(e){this.$message.error('账号列表加载失败');}finally{this.loading=false;}},changePage(p){this.pagination.page=p;this.load();},changeSize(n){this.pagination.page=1;this.pagination.page_size=n;this.load();},open(row){this.form=row?{...row,password:''}:{supplier_id:'',username:'',password:'',active:true};this.visible=true;},async save(){this.saving=true;try{await api.put('/supplier-accounts',{...this.form,password:this.form.password||null});this.visible=false;await this.load();this.$message.success('账号已保存，原登录会话已失效');}catch(e){const d=e.response?.data?.detail;this.$message.error(typeof d==='string'?d:'请检查供应商、登录名及密码长度');}finally{this.saving=false;}}}};
</script>
